# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Protocol

from .methods import (
    ENVIRONMENT_DESCRIBE,
    FILE_COPY,
    FILE_FIND,
    FILE_LIST,
    FILE_MKDIR,
    FILE_MOVE,
    FILE_PATCH,
    FILE_READ,
    FILE_REMOVE,
    FILE_SEARCH,
    FILE_STAT,
    FILE_WRITE,
    INITIALIZE,
    OPERATION_CANCEL,
    OUTPUT_READ,
    OUTPUT_RELEASE,
    PORT_INSPECT,
    PORT_WAIT,
    PROCESS_CLOSE_STDIN,
    PROCESS_INSPECT,
    PROCESS_KILL,
    PROCESS_READ_OUTPUT,
    PROCESS_RELEASE,
    PROCESS_SIGNAL,
    PROCESS_START,
    PROCESS_WAIT,
    PROCESS_WRITE_STDIN,
    RECEIPT_GET,
    SESSION_CLOSE,
    SHELL_EXEC,
    MethodSpec,
)
from .models import (
    EnvironmentDescribeParams,
    EnvironmentDescribeResult,
    FileCopyParams,
    FileCopyResult,
    FileFindParams,
    FileFindResult,
    FileListParams,
    FileListResult,
    FileMkdirParams,
    FileMkdirResult,
    FileMoveParams,
    FileMoveResult,
    FilePatchParams,
    FilePatchResult,
    FileReadParams,
    FileReadResult,
    FileRemoveParams,
    FileRemoveResult,
    FileSearchParams,
    FileSearchResult,
    FileStatParams,
    FileStatResult,
    FileWriteParams,
    FileWriteResult,
    InitializeParams,
    InitializeResult,
    OperationCancelParams,
    OperationCancelResult,
    OutputReadParams,
    OutputReadResult,
    OutputReleaseParams,
    OutputReleaseResult,
    PortInspectParams,
    PortInspectResult,
    PortWaitParams,
    PortWaitResult,
    ProcessCloseStdinParams,
    ProcessCloseStdinResult,
    ProcessInspectParams,
    ProcessInspectResult,
    ProcessKillParams,
    ProcessKillResult,
    ProcessReadOutputParams,
    ProcessReadOutputResult,
    ProcessReleaseParams,
    ProcessReleaseResult,
    ProcessSignalParams,
    ProcessSignalResult,
    ProcessStartParams,
    ProcessStartResult,
    ProcessWaitParams,
    ProcessWaitResult,
    ProcessWriteStdinParams,
    ProcessWriteStdinResult,
    ReceiptGetParams,
    ReceiptGetResult,
    SessionCloseParams,
    SessionCloseResult,
    ShellExecParams,
    ShellExecResult,
)


class EIPRequester(Protocol):
    async def request[P, R](self, method: MethodSpec[P, R], params: P) -> R: ...


class EIPClient:
    def __init__(self, requester: EIPRequester) -> None:
        self._requester = requester

    async def environment_describe(self, params: EnvironmentDescribeParams) -> EnvironmentDescribeResult:
        return await self._requester.request(ENVIRONMENT_DESCRIBE, params)

    async def file_copy(self, params: FileCopyParams) -> FileCopyResult:
        return await self._requester.request(FILE_COPY, params)

    async def file_find(self, params: FileFindParams) -> FileFindResult:
        return await self._requester.request(FILE_FIND, params)

    async def file_list(self, params: FileListParams) -> FileListResult:
        return await self._requester.request(FILE_LIST, params)

    async def file_mkdir(self, params: FileMkdirParams) -> FileMkdirResult:
        return await self._requester.request(FILE_MKDIR, params)

    async def file_move(self, params: FileMoveParams) -> FileMoveResult:
        return await self._requester.request(FILE_MOVE, params)

    async def file_patch(self, params: FilePatchParams) -> FilePatchResult:
        return await self._requester.request(FILE_PATCH, params)

    async def file_read(self, params: FileReadParams) -> FileReadResult:
        return await self._requester.request(FILE_READ, params)

    async def file_remove(self, params: FileRemoveParams) -> FileRemoveResult:
        return await self._requester.request(FILE_REMOVE, params)

    async def file_search(self, params: FileSearchParams) -> FileSearchResult:
        return await self._requester.request(FILE_SEARCH, params)

    async def file_stat(self, params: FileStatParams) -> FileStatResult:
        return await self._requester.request(FILE_STAT, params)

    async def file_write(self, params: FileWriteParams) -> FileWriteResult:
        return await self._requester.request(FILE_WRITE, params)

    async def initialize(self, params: InitializeParams) -> InitializeResult:
        return await self._requester.request(INITIALIZE, params)

    async def operation_cancel(self, params: OperationCancelParams) -> OperationCancelResult:
        return await self._requester.request(OPERATION_CANCEL, params)

    async def output_read(self, params: OutputReadParams) -> OutputReadResult:
        return await self._requester.request(OUTPUT_READ, params)

    async def output_release(self, params: OutputReleaseParams) -> OutputReleaseResult:
        return await self._requester.request(OUTPUT_RELEASE, params)

    async def port_inspect(self, params: PortInspectParams) -> PortInspectResult:
        return await self._requester.request(PORT_INSPECT, params)

    async def port_wait(self, params: PortWaitParams) -> PortWaitResult:
        return await self._requester.request(PORT_WAIT, params)

    async def process_close_stdin(self, params: ProcessCloseStdinParams) -> ProcessCloseStdinResult:
        return await self._requester.request(PROCESS_CLOSE_STDIN, params)

    async def process_inspect(self, params: ProcessInspectParams) -> ProcessInspectResult:
        return await self._requester.request(PROCESS_INSPECT, params)

    async def process_kill(self, params: ProcessKillParams) -> ProcessKillResult:
        return await self._requester.request(PROCESS_KILL, params)

    async def process_read_output(self, params: ProcessReadOutputParams) -> ProcessReadOutputResult:
        return await self._requester.request(PROCESS_READ_OUTPUT, params)

    async def process_release(self, params: ProcessReleaseParams) -> ProcessReleaseResult:
        return await self._requester.request(PROCESS_RELEASE, params)

    async def process_signal(self, params: ProcessSignalParams) -> ProcessSignalResult:
        return await self._requester.request(PROCESS_SIGNAL, params)

    async def process_start(self, params: ProcessStartParams) -> ProcessStartResult:
        return await self._requester.request(PROCESS_START, params)

    async def process_wait(self, params: ProcessWaitParams) -> ProcessWaitResult:
        return await self._requester.request(PROCESS_WAIT, params)

    async def process_write_stdin(self, params: ProcessWriteStdinParams) -> ProcessWriteStdinResult:
        return await self._requester.request(PROCESS_WRITE_STDIN, params)

    async def receipt_get(self, params: ReceiptGetParams) -> ReceiptGetResult:
        return await self._requester.request(RECEIPT_GET, params)

    async def session_close(self, params: SessionCloseParams) -> SessionCloseResult:
        return await self._requester.request(SESSION_CLOSE, params)

    async def shell_exec(self, params: ShellExecParams) -> ShellExecResult:
        return await self._requester.request(SHELL_EXEC, params)
