# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

import json

from pydantic import BaseModel, TypeAdapter


def _object_without_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    value: dict[str, object] = {}
    for key, item in pairs:
        if key in value:
            raise ValueError(f"duplicate JSON field: {key}")
        value[key] = item
    return value


def encode_model(value: BaseModel) -> bytes:
    data = value.model_dump(mode="json", exclude_unset=True)
    return json.dumps(data, ensure_ascii=False, allow_nan=False, separators=(",", ":"), sort_keys=True).encode("utf-8")


def decode_model[T](payload: bytes | str, model_type: type[T]) -> T:
    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")
    data = json.loads(
        payload,
        object_pairs_hook=_object_without_duplicates,
        parse_constant=lambda value: (_ for _ in ()).throw(ValueError(f"invalid JSON number: {value}")),
    )
    return TypeAdapter(model_type).validate_python(data)
