# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal

from .models import (
    EnvironmentChangedNotification,
    EnvironmentDescribeParams,
    EnvironmentDescribeResult,
    FileCopyParams,
    FileCopyResult,
    FileListParams,
    FileListResult,
    FileMkdirParams,
    FileMkdirResult,
    FileMoveParams,
    FileMoveResult,
    FilePatchParams,
    FilePatchResult,
    FileReadParams,
    FileReadResult,
    FileRemoveParams,
    FileRemoveResult,
    FileSearchParams,
    FileSearchResult,
    FileStatParams,
    FileStatResult,
    FileWriteParams,
    FileWriteResult,
    InitializeParams,
    InitializeResult,
    OperationCancelParams,
    OperationCancelResult,
    OutputAvailableNotification,
    OutputReadParams,
    OutputReadResult,
    OutputReleaseParams,
    OutputReleaseResult,
    OutputRetainParams,
    OutputRetainResult,
    PortInspectParams,
    PortInspectResult,
    PortWaitParams,
    PortWaitResult,
    ProcessChangedNotification,
    ProcessCloseStdinParams,
    ProcessCloseStdinResult,
    ProcessInspectParams,
    ProcessInspectResult,
    ProcessKillParams,
    ProcessKillResult,
    ProcessReadOutputParams,
    ProcessReadOutputResult,
    ProcessReleaseParams,
    ProcessReleaseResult,
    ProcessRetainParams,
    ProcessRetainResult,
    ProcessSignalParams,
    ProcessSignalResult,
    ProcessStartParams,
    ProcessStartResult,
    ProcessWaitParams,
    ProcessWaitResult,
    ProcessWriteStdinParams,
    ProcessWriteStdinResult,
    ReceiptGetParams,
    ReceiptGetResult,
    ResourceResolveParams,
    ResourceResolveResult,
    SessionCloseParams,
    SessionCloseResult,
    SessionExpiringNotification,
    ShellExecParams,
    ShellExecResult,
    StateExportParams,
    StateExportResult,
    StateRestoreParams,
    StateRestoreResult,
)


@dataclass(frozen=True, slots=True)
class MethodSpec[P, R]:
    name: str
    capability: str | None
    kind: Literal["request_response", "server_notification"]
    idempotency: str
    idempotency_key: Literal["disallowed", "optional", "required"]
    introduced: str
    error_family: str
    params_type: type[P]
    result_type: type[R] | None


ENVIRONMENT_CHANGED = MethodSpec(
    name="environment.changed",
    capability=None,
    kind="server_notification",
    idempotency="notification",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="notification",
    params_type=EnvironmentChangedNotification,
    result_type=None,
)

ENVIRONMENT_DESCRIBE = MethodSpec(
    name="environment.describe",
    capability="environment.describe",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="common",
    params_type=EnvironmentDescribeParams,
    result_type=EnvironmentDescribeResult,
)

FILE_COPY = MethodSpec(
    name="file.copy",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FileCopyParams,
    result_type=FileCopyResult,
)

FILE_LIST = MethodSpec(
    name="file.list",
    capability="file.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=FileListParams,
    result_type=FileListResult,
)

FILE_MKDIR = MethodSpec(
    name="file.mkdir",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FileMkdirParams,
    result_type=FileMkdirResult,
)

FILE_MOVE = MethodSpec(
    name="file.move",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FileMoveParams,
    result_type=FileMoveResult,
)

FILE_PATCH = MethodSpec(
    name="file.patch",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FilePatchParams,
    result_type=FilePatchResult,
)

FILE_READ = MethodSpec(
    name="file.read",
    capability="file.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=FileReadParams,
    result_type=FileReadResult,
)

FILE_REMOVE = MethodSpec(
    name="file.remove",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FileRemoveParams,
    result_type=FileRemoveResult,
)

FILE_SEARCH = MethodSpec(
    name="file.search",
    capability="file.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=FileSearchParams,
    result_type=FileSearchResult,
)

FILE_STAT = MethodSpec(
    name="file.stat",
    capability="file.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=FileStatParams,
    result_type=FileStatResult,
)

FILE_WRITE = MethodSpec(
    name="file.write",
    capability="file.write",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="resource",
    params_type=FileWriteParams,
    result_type=FileWriteResult,
)

INITIALIZE = MethodSpec(
    name="initialize",
    capability=None,
    kind="request_response",
    idempotency="initialization",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="initialization",
    params_type=InitializeParams,
    result_type=InitializeResult,
)

OPERATION_CANCEL = MethodSpec(
    name="operation.cancel",
    capability="operation.cancel",
    kind="request_response",
    idempotency="state_idempotent_control",
    idempotency_key="optional",
    introduced="1.0",
    error_family="common",
    params_type=OperationCancelParams,
    result_type=OperationCancelResult,
)

OUTPUT_AVAILABLE = MethodSpec(
    name="output.available",
    capability=None,
    kind="server_notification",
    idempotency="notification",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="notification",
    params_type=OutputAvailableNotification,
    result_type=None,
)

OUTPUT_READ = MethodSpec(
    name="output.read",
    capability="output.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="output",
    params_type=OutputReadParams,
    result_type=OutputReadResult,
)

OUTPUT_RELEASE = MethodSpec(
    name="output.release",
    capability="output.read",
    kind="request_response",
    idempotency="state_idempotent_control",
    idempotency_key="optional",
    introduced="1.0",
    error_family="output",
    params_type=OutputReleaseParams,
    result_type=OutputReleaseResult,
)

OUTPUT_RETAIN = MethodSpec(
    name="output.retain",
    capability="output.retain",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="output",
    params_type=OutputRetainParams,
    result_type=OutputRetainResult,
)

PORT_INSPECT = MethodSpec(
    name="port.inspect",
    capability="port.observe",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=PortInspectParams,
    result_type=PortInspectResult,
)

PORT_WAIT = MethodSpec(
    name="port.wait",
    capability="port.observe",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=PortWaitParams,
    result_type=PortWaitResult,
)

PROCESS_CHANGED = MethodSpec(
    name="process.changed",
    capability=None,
    kind="server_notification",
    idempotency="notification",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="notification",
    params_type=ProcessChangedNotification,
    result_type=None,
)

PROCESS_CLOSE_STDIN = MethodSpec(
    name="process.close_stdin",
    capability="process.manage",
    kind="request_response",
    idempotency="state_idempotent_control",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessCloseStdinParams,
    result_type=ProcessCloseStdinResult,
)

PROCESS_INSPECT = MethodSpec(
    name="process.inspect",
    capability="process.manage",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="process",
    params_type=ProcessInspectParams,
    result_type=ProcessInspectResult,
)

PROCESS_KILL = MethodSpec(
    name="process.kill",
    capability="process.manage",
    kind="request_response",
    idempotency="state_idempotent_control",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessKillParams,
    result_type=ProcessKillResult,
)

PROCESS_READ_OUTPUT = MethodSpec(
    name="process.read_output",
    capability="process.manage",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="process",
    params_type=ProcessReadOutputParams,
    result_type=ProcessReadOutputResult,
)

PROCESS_RELEASE = MethodSpec(
    name="process.release",
    capability="process.manage",
    kind="request_response",
    idempotency="state_idempotent_control",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessReleaseParams,
    result_type=ProcessReleaseResult,
)

PROCESS_RETAIN = MethodSpec(
    name="process.retain",
    capability="process.retain",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessRetainParams,
    result_type=ProcessRetainResult,
)

PROCESS_SIGNAL = MethodSpec(
    name="process.signal",
    capability="process.manage",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessSignalParams,
    result_type=ProcessSignalResult,
)

PROCESS_START = MethodSpec(
    name="process.start",
    capability="process.manage",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessStartParams,
    result_type=ProcessStartResult,
)

PROCESS_WAIT = MethodSpec(
    name="process.wait",
    capability="process.manage",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="process",
    params_type=ProcessWaitParams,
    result_type=ProcessWaitResult,
)

PROCESS_WRITE_STDIN = MethodSpec(
    name="process.write_stdin",
    capability="process.manage",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="process",
    params_type=ProcessWriteStdinParams,
    result_type=ProcessWriteStdinResult,
)

RECEIPT_GET = MethodSpec(
    name="receipt.get",
    capability="receipt.read",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="common",
    params_type=ReceiptGetParams,
    result_type=ReceiptGetResult,
)

RESOURCE_RESOLVE = MethodSpec(
    name="resource.resolve",
    capability="resource.resolve",
    kind="request_response",
    idempotency="read_only_retry",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="resource",
    params_type=ResourceResolveParams,
    result_type=ResourceResolveResult,
)

SESSION_CLOSE = MethodSpec(
    name="session.close",
    capability="session.close",
    kind="request_response",
    idempotency="session_terminal",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="session",
    params_type=SessionCloseParams,
    result_type=SessionCloseResult,
)

SESSION_EXPIRING = MethodSpec(
    name="session.expiring",
    capability=None,
    kind="server_notification",
    idempotency="notification",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="notification",
    params_type=SessionExpiringNotification,
    result_type=None,
)

SHELL_EXEC = MethodSpec(
    name="shell.exec",
    capability="shell.exec",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="command",
    params_type=ShellExecParams,
    result_type=ShellExecResult,
)

STATE_EXPORT = MethodSpec(
    name="state.export",
    capability="environment.state",
    kind="request_response",
    idempotency="state_export",
    idempotency_key="disallowed",
    introduced="1.0",
    error_family="state",
    params_type=StateExportParams,
    result_type=StateExportResult,
)

STATE_RESTORE = MethodSpec(
    name="state.restore",
    capability="environment.state",
    kind="request_response",
    idempotency="provider_key_replay",
    idempotency_key="optional",
    introduced="1.0",
    error_family="state",
    params_type=StateRestoreParams,
    result_type=StateRestoreResult,
)

METHODS = MappingProxyType(
    {
        ENVIRONMENT_CHANGED.name: ENVIRONMENT_CHANGED,
        ENVIRONMENT_DESCRIBE.name: ENVIRONMENT_DESCRIBE,
        FILE_COPY.name: FILE_COPY,
        FILE_LIST.name: FILE_LIST,
        FILE_MKDIR.name: FILE_MKDIR,
        FILE_MOVE.name: FILE_MOVE,
        FILE_PATCH.name: FILE_PATCH,
        FILE_READ.name: FILE_READ,
        FILE_REMOVE.name: FILE_REMOVE,
        FILE_SEARCH.name: FILE_SEARCH,
        FILE_STAT.name: FILE_STAT,
        FILE_WRITE.name: FILE_WRITE,
        INITIALIZE.name: INITIALIZE,
        OPERATION_CANCEL.name: OPERATION_CANCEL,
        OUTPUT_AVAILABLE.name: OUTPUT_AVAILABLE,
        OUTPUT_READ.name: OUTPUT_READ,
        OUTPUT_RELEASE.name: OUTPUT_RELEASE,
        OUTPUT_RETAIN.name: OUTPUT_RETAIN,
        PORT_INSPECT.name: PORT_INSPECT,
        PORT_WAIT.name: PORT_WAIT,
        PROCESS_CHANGED.name: PROCESS_CHANGED,
        PROCESS_CLOSE_STDIN.name: PROCESS_CLOSE_STDIN,
        PROCESS_INSPECT.name: PROCESS_INSPECT,
        PROCESS_KILL.name: PROCESS_KILL,
        PROCESS_READ_OUTPUT.name: PROCESS_READ_OUTPUT,
        PROCESS_RELEASE.name: PROCESS_RELEASE,
        PROCESS_RETAIN.name: PROCESS_RETAIN,
        PROCESS_SIGNAL.name: PROCESS_SIGNAL,
        PROCESS_START.name: PROCESS_START,
        PROCESS_WAIT.name: PROCESS_WAIT,
        PROCESS_WRITE_STDIN.name: PROCESS_WRITE_STDIN,
        RECEIPT_GET.name: RECEIPT_GET,
        RESOURCE_RESOLVE.name: RESOURCE_RESOLVE,
        SESSION_CLOSE.name: SESSION_CLOSE,
        SESSION_EXPIRING.name: SESSION_EXPIRING,
        SHELL_EXEC.name: SHELL_EXEC,
        STATE_EXPORT.name: STATE_EXPORT,
        STATE_RESTORE.name: STATE_RESTORE,
    }
)
REQUEST_METHODS = MappingProxyType(
    {name: method for name, method in METHODS.items() if method.kind == "request_response"}
)
NOTIFICATION_METHODS = MappingProxyType(
    {name: method for name, method in METHODS.items() if method.kind == "server_notification"}
)
