# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

import base64
import binascii
import re
from collections.abc import Mapping
from datetime import UTC, datetime
from enum import StrEnum
from types import MappingProxyType
from typing import Annotated, Final, Literal

from pydantic import (
    AfterValidator,
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictInt,
    StrictStr,
    model_validator,
)


def _validate_absolute_eip_path(value: str) -> str:
    if not value.startswith("/") or "\x00" in value:
        raise ValueError("EIP paths must be absolute UTF-8 paths without NUL")
    if value != "/" and (value.endswith("/") or any(part in {"", ".", ".."} for part in value.split("/")[1:])):
        raise ValueError("EIP paths must be canonical lexical mount paths")
    return value


def _validate_base64_unpadded(value: str) -> str:
    if "=" in value or re.fullmatch(r"[A-Za-z0-9+/]*", value) is None:
        raise ValueError("encoded bytes must use unpadded base64")
    try:
        decoded = base64.b64decode(value + ("=" * (-len(value) % 4)), validate=True)
    except (binascii.Error, ValueError) as error:
        raise ValueError("encoded bytes must use unpadded base64") from error
    if base64.b64encode(decoded).decode("ascii").rstrip("=") != value:
        raise ValueError("encoded bytes must use canonical unpadded base64")
    return value


def _timestamp_fraction(nanoseconds: int) -> str:
    if nanoseconds == 0:
        return ""
    if nanoseconds % 1_000_000 == 0:
        return f".{nanoseconds // 1_000_000:03d}"
    if nanoseconds % 1_000 == 0:
        return f".{nanoseconds // 1_000:06d}"
    return f".{nanoseconds:09d}"


def _normalize_eip_timestamp(value: object) -> str:
    if isinstance(value, datetime):
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("EIP timestamps must include a UTC offset")
        nanoseconds = value.microsecond * 1_000
        normalized = value.astimezone(UTC).replace(microsecond=0)
    elif isinstance(value, str):
        match = re.fullmatch(
            r"(?P<base>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2})"
            r"(?:\.(?P<fraction>[0-9]{1,9}))?(?P<zone>Z|[+-][0-9]{2}:[0-9]{2})",
            value,
        )
        if match is None:
            raise ValueError("EIP timestamps must use RFC 3339 syntax")
        fraction = match.group("fraction") or ""
        nanoseconds = int(fraction.ljust(9, "0")) if fraction else 0
        zone = match.group("zone")
        offset = "+00:00" if zone == "Z" else zone
        try:
            normalized = datetime.fromisoformat(f"{match.group('base')}{offset}").astimezone(UTC)
        except ValueError as error:
            raise ValueError("EIP timestamp is outside the RFC 3339 calendar") from error
    else:
        raise ValueError("EIP timestamps must be RFC 3339 strings or datetime values")
    prefix = (
        f"{normalized.year:04d}-{normalized.month:02d}-{normalized.day:02d}"
        f"T{normalized.hour:02d}:{normalized.minute:02d}:{normalized.second:02d}"
    )
    return "".join(prefix) + _timestamp_fraction(nanoseconds) + "Z"


Identifier = Annotated[StrictStr, Field(min_length=1)]
AbsoluteEIPPath = Annotated[
    StrictStr,
    Field(json_schema_extra={"format": "eip-absolute-path"}),
    AfterValidator(_validate_absolute_eip_path),
]
Base64Unpadded = Annotated[
    StrictStr,
    Field(json_schema_extra={"format": "eip-base64-unpadded"}),
    AfterValidator(_validate_base64_unpadded),
]
ProtocolVersion = Annotated[StrictStr, Field(pattern=r"^[1-9][0-9]*\.[0-9]+$")]
EIPTimestamp = Annotated[
    StrictStr,
    Field(json_schema_extra={"format": "date-time"}),
    BeforeValidator(_normalize_eip_timestamp),
]


class EIPModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class CleanupOutcome(StrEnum):
    PENDING = "pending"
    COMPLETE = "complete"
    RESIDUAL_CONFINED = "residual_confined"
    FAILED = "failed"


class CommandNetwork(StrEnum):
    CONFIGURED = "configured"
    DENY = "deny"


class DesiredPortStatus(StrEnum):
    LISTENING = "listening"
    NOT_LISTENING = "not_listening"


class DispatchStage(StrEnum):
    PRE_DISPATCH = "pre_dispatch"
    DISPATCHING = "dispatching"
    DISPATCHED = "dispatched"
    COMPLETED = "completed"
    UNKNOWN = "unknown"


class ErrorType(StrEnum):
    PARSE_ERROR = "parse_error"
    INVALID_REQUEST = "invalid_request"
    METHOD_NOT_FOUND = "method_not_found"
    INVALID_PARAMS = "invalid_params"
    INTERNAL_ERROR = "internal_error"
    NOT_INITIALIZED = "not_initialized"
    ALREADY_INITIALIZED = "already_initialized"
    PROTOCOL_INCOMPATIBLE = "protocol_incompatible"
    DENIED = "denied"
    NOT_FOUND_OR_DENIED = "not_found_or_denied"
    UNSUPPORTED = "unsupported"
    STALE_GENERATION = "stale_generation"
    INVALID_HANDLE = "invalid_handle"
    RETENTION_GAP = "retention_gap"
    BUSY = "busy"
    QUOTA_EXCEEDED = "quota_exceeded"
    OUTPUT_LIMIT_EXCEEDED = "output_limit_exceeded"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"
    UNKNOWN_OUTCOME = "unknown_outcome"
    OPERATION_IN_PROGRESS = "operation_in_progress"
    IDEMPOTENCY_CONFLICT = "idempotency_conflict"
    PROVIDER_UNAVAILABLE = "provider_unavailable"
    EXECUTION_ISOLATION_FAILED = "execution_isolation_failed"
    CLEANUP_FAILED = "cleanup_failed"
    COMMAND_START_FAILED = "command_start_failed"
    CONFLICT = "conflict"


class FileKind(StrEnum):
    FILE = "file"
    DIRECTORY = "directory"
    SYMLINK = "symlink"
    OTHER = "other"


class FindMode(StrEnum):
    GLOB = "glob"
    REGEX = "regex"


class IsolationBackend(StrEnum):
    LINUX_BUBBLEWRAP = "linux_bubblewrap"
    MACOS_SEATBELT = "macos_seatbelt"
    OUTER_HOST = "outer_host"


class IsolationCleanupGuarantee(StrEnum):
    NAMESPACE_COMPLETE = "namespace_complete"
    RESIDUAL_CONFINED_POSSIBLE = "residual_confined_possible"
    OUTER_HOST = "outer_host"


class IsolationMode(StrEnum):
    REQUIRED = "required"
    DISABLED = "disabled"


class IsolationNetworkPolicy(StrEnum):
    HOST = "host"
    DENY = "deny"


class OperationCancelStatus(StrEnum):
    NOT_FOUND = "not_found"
    ALREADY_TERMINAL = "already_terminal"
    CANCELLATION_REQUESTED = "cancellation_requested"
    NOT_CANCELLABLE = "not_cancellable"


class OutputKind(StrEnum):
    EMPTY = "empty"
    INLINE = "inline"
    RETAINED = "retained"
    TRUNCATED = "truncated"


class OutputOverflow(StrEnum):
    FAIL = "fail"
    TRUNCATE = "truncate"
    RETAIN = "retain"


class PortAddress(StrEnum):
    LOOPBACK = "loopback"
    ANY = "any"


class PortStatus(StrEnum):
    LISTENING = "listening"
    NOT_LISTENING = "not_listening"
    UNKNOWN = "unknown"


class ProcessPhase(StrEnum):
    STARTING = "starting"
    RUNNING = "running"
    EXITED = "exited"
    SIGNALED = "signaled"
    TIMED_OUT = "timed_out"
    CANCELLED = "cancelled"
    FAILED = "failed"


class ProcessSignal(StrEnum):
    INTERRUPT = "interrupt"
    TERMINATE = "terminate"
    KILL = "kill"


class ProcessStream(StrEnum):
    STDOUT = "stdout"
    STDERR = "stderr"


class ProcessWaitCondition(StrEnum):
    INITIAL_TERMINAL = "initial_terminal"
    TREE_CLEANED = "tree_cleaned"


class ReceiptOutcome(StrEnum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
    TIMED_OUT = "timed_out"
    UNKNOWN = "unknown"


class ReceiptStage(StrEnum):
    ACCEPTED = "accepted"
    DISPATCHED = "dispatched"
    EXEC_CONFIRMED = "exec_confirmed"
    COMPLETED = "completed"
    UNKNOWN = "unknown"


class RequestedProcessSignal(StrEnum):
    INTERRUPT = "interrupt"
    TERMINATE = "terminate"


class RetryHint(StrEnum):
    NEVER = "never"
    SAME_REQUEST = "same_request"
    AFTER_REFRESH = "after_refresh"
    AFTER_CAPACITY = "after_capacity"
    AFTER_AUTHORITY_CHANGE = "after_authority_change"
    RECONCILE_FIRST = "reconcile_first"


class SearchMode(StrEnum):
    LITERAL = "literal"
    REGEX = "regex"


class TerminationReason(StrEnum):
    EXIT = "exit"
    SIGNAL = "signal"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"
    OUTPUT_LIMIT = "output_limit"
    BACKEND_LOST = "backend_lost"


class WriteMode(StrEnum):
    CREATE = "create"
    REPLACE = "replace"
    UPSERT = "upsert"
    APPEND = "append"
    WRITE_AT = "write_at"


EIP_ERROR_CODES: Final[Mapping[ErrorType, int]] = MappingProxyType(
    {
        ErrorType.PARSE_ERROR: -32700,
        ErrorType.INVALID_REQUEST: -32600,
        ErrorType.METHOD_NOT_FOUND: -32601,
        ErrorType.INVALID_PARAMS: -32602,
        ErrorType.INTERNAL_ERROR: -32603,
        ErrorType.NOT_INITIALIZED: -32001,
        ErrorType.ALREADY_INITIALIZED: -32002,
        ErrorType.PROTOCOL_INCOMPATIBLE: -32003,
        ErrorType.DENIED: -32010,
        ErrorType.NOT_FOUND_OR_DENIED: -32011,
        ErrorType.UNSUPPORTED: -32012,
        ErrorType.STALE_GENERATION: -32020,
        ErrorType.INVALID_HANDLE: -32021,
        ErrorType.RETENTION_GAP: -32022,
        ErrorType.BUSY: -32030,
        ErrorType.QUOTA_EXCEEDED: -32031,
        ErrorType.OUTPUT_LIMIT_EXCEEDED: -32032,
        ErrorType.TIMEOUT: -32040,
        ErrorType.CANCELLED: -32041,
        ErrorType.UNKNOWN_OUTCOME: -32042,
        ErrorType.OPERATION_IN_PROGRESS: -32043,
        ErrorType.IDEMPOTENCY_CONFLICT: -32044,
        ErrorType.PROVIDER_UNAVAILABLE: -32050,
        ErrorType.EXECUTION_ISOLATION_FAILED: -32051,
        ErrorType.CLEANUP_FAILED: -32052,
        ErrorType.COMMAND_START_FAILED: -32053,
        ErrorType.CONFLICT: -32060,
    }
)


class ArgvCommand(EIPModel):
    kind: Literal["argv"]
    executable: StrictStr
    arguments: tuple[StrictStr, ...] = ()


class CommandEnvironment(EIPModel):
    set: dict[StrictStr, StrictStr] = Field(default_factory=dict)
    unset: tuple[StrictStr, ...] = ()


class CommandLimits(EIPModel):
    wall_time_ms: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    stdin_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    process_count: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    memory_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    cpu_time_ms: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None


class EIPCallContext(EIPModel):
    operation_id: Identifier
    deadline: EIPTimestamp | None = None
    idempotency_key: Identifier | None = None


class EIPClientInfo(EIPModel):
    name: StrictStr
    version: StrictStr


class EIPLimits(EIPModel):
    max_request_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_response_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_concurrent_operations: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_processes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_operation_duration_ms: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_inline_output_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_output_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_retained_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_retained_objects: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_retention_ttl_ms: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_operation_records: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    operation_record_ttl_ms: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    session_idle_ttl_ms: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_process_records: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    terminal_process_record_ttl_ms: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]

    @model_validator(mode="after")
    def _validate_limit_relationships(self) -> EIPLimits:
        if self.max_inline_output_bytes > self.max_output_bytes:
            raise ValueError("max_inline_output_bytes cannot exceed max_output_bytes")
        if self.max_processes > self.max_process_records:
            raise ValueError("max_processes cannot exceed max_process_records")
        if self.max_concurrent_operations > self.max_operation_records:
            raise ValueError("max_concurrent_operations cannot exceed max_operation_records")
        return self


class EIPPath(EIPModel):
    mount_id: Identifier
    path: AbsoluteEIPPath


class EIPServerInfo(EIPModel):
    name: Literal["agent-envd"]
    version: StrictStr


class EncodedBytes(EIPModel):
    encoding: Literal["base64"]
    data: Base64Unpadded


class EnvironmentDescribeParams(EIPModel):
    context: EIPCallContext


class FileMkdirParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    parents: StrictBool = False
    exist_ok: StrictBool = False


class FileRevision(RootModel[Identifier]):
    model_config = ConfigDict(frozen=True)
    root: Identifier


class FileSearchMatch(EIPModel):
    path: EIPPath
    line_number: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    byte_offset: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    preview: StrictStr


class FileStatParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    follow_symlinks: StrictBool = True


class FileWriteParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    mode: WriteMode
    data: EncodedBytes
    offset: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    expected_revision: FileRevision | None = None
    create_parents: StrictBool = False
    executable: StrictBool | None = None


class InitializeParams(EIPModel):
    supported_protocol_versions: Annotated[tuple[StrictStr, ...], Field(min_length=1)]
    client: EIPClientInfo
    expected_environment_id: Identifier
    required_capabilities: tuple[StrictStr, ...] = ()
    optional_capabilities: tuple[StrictStr, ...] = ()


class IsolationPosture(EIPModel):
    mode: IsolationMode
    backend: IsolationBackend
    filesystem_containment: StrictBool
    process_containment: StrictBool
    network_containment: StrictBool
    network_policy: IsolationNetworkPolicy
    cleanup_guarantee: IsolationCleanupGuarantee


class MountDescriptor(EIPModel):
    mount_id: Identifier
    logical_root: AbsoluteEIPPath
    writable: StrictBool
    case_sensitive: StrictBool | None = None
    supports_atomic_replace: StrictBool
    supports_file_revision: StrictBool
    max_file_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]


class OperationCancelParams(EIPModel):
    context: EIPCallContext
    target_operation_id: Identifier


class OperationCancelResult(EIPModel):
    status: OperationCancelStatus


class OutputCursor(RootModel[Identifier]):
    model_config = ConfigDict(frozen=True)
    root: Identifier


class OutputPolicy(EIPModel):
    max_inline_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    max_output_bytes: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    overflow: OutputOverflow

    @model_validator(mode="after")
    def _validate_output_bounds(self) -> OutputPolicy:
        if self.max_inline_bytes > self.max_output_bytes:
            raise ValueError("max_inline_bytes cannot exceed max_output_bytes")
        return self


class OutputReference(RootModel[Identifier]):
    model_config = ConfigDict(frozen=True)
    root: Identifier


class OutputReleaseParams(EIPModel):
    context: EIPCallContext
    reference: OutputReference | None = None
    cursor: OutputCursor | None = None

    @model_validator(mode="after")
    def _validate_selector(self) -> OutputReleaseParams:
        present = sum(
            value is not None
            for value in (
                self.reference,
                self.cursor,
            )
        )
        if present != 1:
            raise ValueError("exactly one of reference, cursor must be present")
        return self


class OutputSegment(EIPModel):
    start_offset: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    data: EncodedBytes


class PortTarget(EIPModel):
    protocol: Literal["tcp"]
    address: PortAddress
    port: Annotated[StrictInt, Field(ge=1, le=65535)]


class PortWaitParams(EIPModel):
    context: EIPCallContext
    target: PortTarget
    desired_status: DesiredPortStatus


class ProcessHandle(RootModel[Identifier]):
    model_config = ConfigDict(frozen=True)
    root: Identifier


class ProcessInspectParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle


class ProcessKillParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle


class ProcessReadOutputParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle
    stdout_cursor: OutputCursor | None = None
    stderr_cursor: OutputCursor | None = None
    wait_ms: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] = 0
    output_policy: OutputPolicy | None = None


class ProcessReleaseParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle


class ProcessSignalParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle
    signal: RequestedProcessSignal


class ProcessStatus(EIPModel):
    phase: ProcessPhase
    termination_reason: TerminationReason | None = None
    exit_code: Annotated[StrictInt, Field(ge=-2147483648, le=2147483647)] | None = None
    signal: ProcessSignal | None = None
    started_at: EIPTimestamp | None = None
    ended_at: EIPTimestamp | None = None
    cleanup: CleanupOutcome


class ProcessWaitParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle
    condition: ProcessWaitCondition


class ProcessWriteStdinParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle
    data: EncodedBytes
    close_after_write: StrictBool = False


class ReceiptRef(RootModel[Identifier]):
    model_config = ConfigDict(frozen=True)
    root: Identifier


class SessionCloseParams(EIPModel):
    context: EIPCallContext


class SessionCloseResult(EIPModel):
    closed: Literal[True]


class ShellCommand(EIPModel):
    kind: Literal["shell"]
    profile_id: Identifier
    script: StrictStr
    login: StrictBool = False


class ShellProfileDescriptor(EIPModel):
    profile_id: Identifier
    display_name: StrictStr
    supports_login_mode: StrictBool
    max_script_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]


class StructuredOutputDisposition(EIPModel):
    producer_complete: StrictBool
    content_complete: StrictBool
    emitted_items: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    dropped_items: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    encoded_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    cursor: OutputCursor | None = None
    expires_at: EIPTimestamp | None = None


type CommandSpec = Annotated[
    ArgvCommand | ShellCommand,
    Field(discriminator="kind"),
]


class EnvironmentDescriptor(EIPModel):
    environment_id: Identifier
    generation: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    capabilities: tuple[StrictStr, ...] = ()
    mounts: tuple[MountDescriptor, ...] = ()
    shell_profiles: tuple[ShellProfileDescriptor, ...] = ()
    limits: EIPLimits
    isolation: IsolationPosture


class FileCopyParams(EIPModel):
    context: EIPCallContext
    source: EIPPath
    destination: EIPPath
    expected_source_revision: FileRevision | None = None
    expected_destination_revision: FileRevision | None = None
    replace: StrictBool = False
    require_atomic_destination: StrictBool = False


class FileFindParams(EIPModel):
    context: EIPCallContext
    root: EIPPath
    pattern: StrictStr
    mode: FindMode
    kind: FileKind | None = None
    max_depth: Annotated[StrictInt, Field(ge=0, le=4294967295)]
    cursor: OutputCursor | None = None
    output_policy: OutputPolicy | None = None


class FileInfo(EIPModel):
    path: EIPPath
    kind: FileKind
    size_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    modified_at: EIPTimestamp | None = None
    executable: StrictBool | None = None
    revision: FileRevision | None = None


class FileListEntry(EIPModel):
    relative_path: StrictStr
    info: FileInfo


class FileListParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    recursive: StrictBool = False
    max_depth: Annotated[StrictInt, Field(ge=0, le=4294967295)] = 1
    cursor: OutputCursor | None = None
    output_policy: OutputPolicy | None = None


class FileListResult(EIPModel):
    entries: tuple[FileListEntry, ...] = ()
    output: StructuredOutputDisposition


class FileMoveParams(EIPModel):
    context: EIPCallContext
    source: EIPPath
    destination: EIPPath
    expected_source_revision: FileRevision | None = None
    expected_destination_revision: FileRevision | None = None
    replace: StrictBool = False


class FilePatchParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    patch_format: Literal["unified_diff"]
    patch: StrictStr
    expected_revision: FileRevision


class FileReadParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    offset: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] = 0
    length: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    expected_revision: FileRevision | None = None
    output_policy: OutputPolicy | None = None


class FileRemoveParams(EIPModel):
    context: EIPCallContext
    path: EIPPath
    expected_kind: FileKind
    expected_revision: FileRevision | None = None
    recursive: StrictBool = False
    max_entries: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] = 1


class FileSearchParams(EIPModel):
    context: EIPCallContext
    root: EIPPath
    query: StrictStr
    mode: SearchMode
    include: tuple[StrictStr, ...] = ()
    exclude: tuple[StrictStr, ...] = ()
    max_depth: Annotated[StrictInt, Field(ge=0, le=4294967295)]
    cursor: OutputCursor | None = None
    output_policy: OutputPolicy | None = None
    case_sensitive: StrictBool = True


class FileSearchResult(EIPModel):
    matches: tuple[FileSearchMatch, ...] = ()
    output: StructuredOutputDisposition


class FileStatResult(EIPModel):
    info: FileInfo


class InitializeResult(EIPModel):
    protocol_version: ProtocolVersion
    server: EIPServerInfo
    descriptor: EnvironmentDescriptor


class OperationReceipt(EIPModel):
    receipt_ref: ReceiptRef
    operation_id: Identifier
    method: StrictStr
    environment_id: Identifier
    generation: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    request_digest: StrictStr
    stage: ReceiptStage
    outcome: ReceiptOutcome | None = None
    observed_at: EIPTimestamp


class OutputPreview(EIPModel):
    segments: tuple[OutputSegment, ...] = ()
    represented_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]


class OutputReadParams(EIPModel):
    context: EIPCallContext
    reference: OutputReference
    cursor: OutputCursor | None = None
    start_offset: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    output_policy: OutputPolicy | None = None

    @model_validator(mode="after")
    def _validate_position(self) -> OutputReadParams:
        present = sum(
            value is not None
            for value in (
                self.cursor,
                self.start_offset,
            )
        )
        if present != 1:
            raise ValueError("exactly one of cursor, start_offset must be present")
        return self


class OutputReleaseResult(EIPModel):
    released: StrictBool
    receipt: OperationReceipt


class PortInspectParams(EIPModel):
    context: EIPCallContext
    target: PortTarget


class PortObservation(EIPModel):
    target: PortTarget
    status: PortStatus
    managed_process: ProcessHandle | None = None
    observed_at: EIPTimestamp


class PortWaitResult(EIPModel):
    observation: PortObservation


class ProcessCloseStdinParams(EIPModel):
    context: EIPCallContext
    handle: ProcessHandle


class ProcessCloseStdinResult(EIPModel):
    stdin_open: Literal[False]
    receipt: OperationReceipt


class ProcessReleaseResult(EIPModel):
    released: StrictBool
    receipt: OperationReceipt


class ProcessWriteStdinResult(EIPModel):
    accepted_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    stdin_open: StrictBool
    receipt: OperationReceipt


class ReceiptGetParams(EIPModel):
    context: EIPCallContext
    receipt_ref: ReceiptRef | None = None
    operation_id: Identifier | None = None

    @model_validator(mode="after")
    def _validate_selector(self) -> ReceiptGetParams:
        present = sum(
            value is not None
            for value in (
                self.receipt_ref,
                self.operation_id,
            )
        )
        if present != 1:
            raise ValueError("exactly one of receipt_ref, operation_id must be present")
        return self


class ReceiptGetResult(EIPModel):
    receipt: OperationReceipt


class CommandRequest(EIPModel):
    command: CommandSpec
    cwd: EIPPath
    environment: CommandEnvironment = Field(default_factory=CommandEnvironment)
    network: CommandNetwork = CommandNetwork("configured")
    limits: CommandLimits = Field(default_factory=CommandLimits)
    initial_stdin: EncodedBytes | None = None
    keep_stdin_open: StrictBool = False
    output_policy: OutputPolicy | None = None


class EIPErrorData(EIPModel):
    error_type: ErrorType
    retry_hint: RetryHint
    dispatch_stage: DispatchStage
    operation_id: Identifier | None = None
    environment_id: Identifier | None = None
    generation: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)] | None = None
    capability: StrictStr | None = None
    field: StrictStr | None = None
    handle_kind: StrictStr | None = None
    produced_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    captured_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    dropped_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    emitted_items: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    dropped_items: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    process_status: ProcessStatus | None = None
    receipt: OperationReceipt | None = None
    safe_detail: StrictStr | None = None
    available_start: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None
    available_end: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)] | None = None

    @model_validator(mode="after")
    def _validate_retention_gap_bounds(self) -> EIPErrorData:
        available_start = self.available_start
        available_end = self.available_end
        has_start = available_start is not None
        has_end = available_end is not None
        if has_start != has_end:
            raise ValueError("available_start and available_end must be present together")
        if self.error_type is ErrorType.RETENTION_GAP and not has_start:
            raise ValueError("retention_gap requires available bounds")
        if available_start is not None and available_end is not None and available_start > available_end:
            raise ValueError("available_start cannot exceed available_end")
        return self


class EnvironmentDescribeResult(EIPModel):
    descriptor: EnvironmentDescriptor


class FileCopyResult(EIPModel):
    destination: FileInfo
    bytes_copied: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    atomic_destination: StrictBool
    receipt: OperationReceipt


class FileFindResult(EIPModel):
    entries: tuple[FileListEntry, ...] = ()
    output: StructuredOutputDisposition


class FileMkdirResult(EIPModel):
    info: FileInfo
    created_directories: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    receipt: OperationReceipt


class FileMoveResult(EIPModel):
    destination: FileInfo
    receipt: OperationReceipt


class FilePatchResult(EIPModel):
    info: FileInfo
    hunks_applied: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    receipt: OperationReceipt


class FileRemoveResult(EIPModel):
    removed_entries: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    receipt: OperationReceipt


class FileWriteResult(EIPModel):
    info: FileInfo
    bytes_written: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    receipt: OperationReceipt


class OutputCapture(EIPModel):
    kind: OutputKind
    producer_complete: StrictBool
    content_complete: StrictBool
    produced_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    captured_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    dropped_bytes: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    inline: EncodedBytes | None = None
    preview: OutputPreview | None = None
    reference: OutputReference | None = None
    cursor: OutputCursor | None = None
    available_start: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    available_end: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    expires_at: EIPTimestamp | None = None

    @model_validator(mode="after")
    def _validate_capture_structure(self) -> OutputCapture:
        if self.available_start > self.available_end:
            raise ValueError("available_start cannot exceed available_end")
        if self.kind is OutputKind.EMPTY:
            if (
                self.produced_bytes != 0
                or self.captured_bytes != 0
                or self.dropped_bytes != 0
                or self.available_start != 0
                or self.available_end != 0
                or any(
                    value is not None
                    for value in (
                        self.inline,
                        self.preview,
                        self.reference,
                        self.cursor,
                        self.expires_at,
                    )
                )
            ):
                raise ValueError("empty output must contain no bytes or retained state")
        elif self.kind is OutputKind.INLINE:
            if self.inline is None or any(
                value is not None for value in (self.preview, self.reference, self.cursor, self.expires_at)
            ):
                raise ValueError("inline output requires only inline data")
        elif self.kind is OutputKind.RETAINED:
            if self.reference is None or self.inline is not None or self.expires_at is None:
                raise ValueError("retained output requires a reference and expiry")
        elif self.kind is OutputKind.TRUNCATED and any(
            value is not None for value in (self.inline, self.reference, self.cursor, self.expires_at)
        ):
            raise ValueError("truncated output cannot contain retained or inline state")
        return self


class OutputReadResult(EIPModel):
    chunks: tuple[OutputSegment, ...] = ()
    next_cursor: OutputCursor | None = None
    capture: OutputCapture


class PortInspectResult(EIPModel):
    observation: PortObservation


class ProcessStartParams(EIPModel):
    context: EIPCallContext
    request: CommandRequest


class ProcessStreamRead(EIPModel):
    chunks: tuple[OutputSegment, ...] = ()
    next_cursor: OutputCursor | None = None
    capture: OutputCapture


class ProcessStreamSnapshot(EIPModel):
    stream: ProcessStream
    capture: OutputCapture


class ShellExecParams(EIPModel):
    context: EIPCallContext
    request: CommandRequest


class EIPError(EIPModel):
    code: Annotated[StrictInt, Field(ge=-2147483648, le=2147483647)]
    message: StrictStr
    data: EIPErrorData

    @model_validator(mode="after")
    def _validate_error_code(self) -> EIPError:
        if self.code != EIP_ERROR_CODES[self.data.error_type]:
            raise ValueError("JSON-RPC code does not match error_type")
        return self


class FileReadResult(EIPModel):
    info: FileInfo
    range_start: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    range_end: Annotated[StrictInt, Field(ge=0, le=18446744073709551615)]
    output: OutputCapture


class ProcessOutputSnapshot(EIPModel):
    stdout: ProcessStreamSnapshot
    stderr: ProcessStreamSnapshot


class ShellExecResult(EIPModel):
    status: ProcessStatus
    output: ProcessOutputSnapshot
    receipt: OperationReceipt


class ProcessInfo(EIPModel):
    handle: ProcessHandle
    environment_id: Identifier
    generation: Annotated[StrictInt, Field(ge=1, le=18446744073709551615)]
    status: ProcessStatus
    stdin_open: StrictBool
    output: ProcessOutputSnapshot


class ProcessInspectResult(EIPModel):
    process: ProcessInfo


class ProcessKillResult(EIPModel):
    process: ProcessInfo
    receipt: OperationReceipt


class ProcessReadOutputResult(EIPModel):
    process: ProcessInfo
    stdout: ProcessStreamRead
    stderr: ProcessStreamRead


class ProcessSignalResult(EIPModel):
    accepted: StrictBool
    process: ProcessInfo
    receipt: OperationReceipt


class ProcessStartResult(EIPModel):
    process: ProcessInfo
    receipt: OperationReceipt


class ProcessWaitResult(EIPModel):
    process: ProcessInfo


ArgvCommand.model_rebuild()
CommandEnvironment.model_rebuild()
CommandLimits.model_rebuild()
EIPCallContext.model_rebuild()
EIPClientInfo.model_rebuild()
EIPLimits.model_rebuild()
EIPPath.model_rebuild()
EIPServerInfo.model_rebuild()
EncodedBytes.model_rebuild()
EnvironmentDescribeParams.model_rebuild()
FileMkdirParams.model_rebuild()
FileSearchMatch.model_rebuild()
FileStatParams.model_rebuild()
FileWriteParams.model_rebuild()
InitializeParams.model_rebuild()
IsolationPosture.model_rebuild()
MountDescriptor.model_rebuild()
OperationCancelParams.model_rebuild()
OperationCancelResult.model_rebuild()
OutputPolicy.model_rebuild()
OutputReleaseParams.model_rebuild()
OutputSegment.model_rebuild()
PortTarget.model_rebuild()
PortWaitParams.model_rebuild()
ProcessInspectParams.model_rebuild()
ProcessKillParams.model_rebuild()
ProcessReadOutputParams.model_rebuild()
ProcessReleaseParams.model_rebuild()
ProcessSignalParams.model_rebuild()
ProcessStatus.model_rebuild()
ProcessWaitParams.model_rebuild()
ProcessWriteStdinParams.model_rebuild()
SessionCloseParams.model_rebuild()
SessionCloseResult.model_rebuild()
ShellCommand.model_rebuild()
ShellProfileDescriptor.model_rebuild()
StructuredOutputDisposition.model_rebuild()
EnvironmentDescriptor.model_rebuild()
FileCopyParams.model_rebuild()
FileFindParams.model_rebuild()
FileInfo.model_rebuild()
FileListEntry.model_rebuild()
FileListParams.model_rebuild()
FileListResult.model_rebuild()
FileMoveParams.model_rebuild()
FilePatchParams.model_rebuild()
FileReadParams.model_rebuild()
FileRemoveParams.model_rebuild()
FileSearchParams.model_rebuild()
FileSearchResult.model_rebuild()
FileStatResult.model_rebuild()
InitializeResult.model_rebuild()
OperationReceipt.model_rebuild()
OutputPreview.model_rebuild()
OutputReadParams.model_rebuild()
OutputReleaseResult.model_rebuild()
PortInspectParams.model_rebuild()
PortObservation.model_rebuild()
PortWaitResult.model_rebuild()
ProcessCloseStdinParams.model_rebuild()
ProcessCloseStdinResult.model_rebuild()
ProcessReleaseResult.model_rebuild()
ProcessWriteStdinResult.model_rebuild()
ReceiptGetParams.model_rebuild()
ReceiptGetResult.model_rebuild()
CommandRequest.model_rebuild()
EIPErrorData.model_rebuild()
EnvironmentDescribeResult.model_rebuild()
FileCopyResult.model_rebuild()
FileFindResult.model_rebuild()
FileMkdirResult.model_rebuild()
FileMoveResult.model_rebuild()
FilePatchResult.model_rebuild()
FileRemoveResult.model_rebuild()
FileWriteResult.model_rebuild()
OutputCapture.model_rebuild()
OutputReadResult.model_rebuild()
PortInspectResult.model_rebuild()
ProcessStartParams.model_rebuild()
ProcessStreamRead.model_rebuild()
ProcessStreamSnapshot.model_rebuild()
ShellExecParams.model_rebuild()
EIPError.model_rebuild()
FileReadResult.model_rebuild()
ProcessOutputSnapshot.model_rebuild()
ShellExecResult.model_rebuild()
ProcessInfo.model_rebuild()
ProcessInspectResult.model_rebuild()
ProcessKillResult.model_rebuild()
ProcessReadOutputResult.model_rebuild()
ProcessSignalResult.model_rebuild()
ProcessStartResult.model_rebuild()
ProcessWaitResult.model_rebuild()

__all__ = [
    "EIP_ERROR_CODES",
    "ArgvCommand",
    "CleanupOutcome",
    "CommandEnvironment",
    "CommandLimits",
    "CommandNetwork",
    "CommandRequest",
    "CommandSpec",
    "DesiredPortStatus",
    "DispatchStage",
    "EIPCallContext",
    "EIPClientInfo",
    "EIPError",
    "EIPErrorData",
    "EIPLimits",
    "EIPPath",
    "EIPServerInfo",
    "EncodedBytes",
    "EnvironmentDescribeParams",
    "EnvironmentDescribeResult",
    "EnvironmentDescriptor",
    "ErrorType",
    "FileCopyParams",
    "FileCopyResult",
    "FileFindParams",
    "FileFindResult",
    "FileInfo",
    "FileKind",
    "FileListEntry",
    "FileListParams",
    "FileListResult",
    "FileMkdirParams",
    "FileMkdirResult",
    "FileMoveParams",
    "FileMoveResult",
    "FilePatchParams",
    "FilePatchResult",
    "FileReadParams",
    "FileReadResult",
    "FileRemoveParams",
    "FileRemoveResult",
    "FileRevision",
    "FileSearchMatch",
    "FileSearchParams",
    "FileSearchResult",
    "FileStatParams",
    "FileStatResult",
    "FileWriteParams",
    "FileWriteResult",
    "FindMode",
    "InitializeParams",
    "InitializeResult",
    "IsolationBackend",
    "IsolationCleanupGuarantee",
    "IsolationMode",
    "IsolationNetworkPolicy",
    "IsolationPosture",
    "MountDescriptor",
    "OperationCancelParams",
    "OperationCancelResult",
    "OperationCancelStatus",
    "OperationReceipt",
    "OutputCapture",
    "OutputCursor",
    "OutputKind",
    "OutputOverflow",
    "OutputPolicy",
    "OutputPreview",
    "OutputReadParams",
    "OutputReadResult",
    "OutputReference",
    "OutputReleaseParams",
    "OutputReleaseResult",
    "OutputSegment",
    "PortAddress",
    "PortInspectParams",
    "PortInspectResult",
    "PortObservation",
    "PortStatus",
    "PortTarget",
    "PortWaitParams",
    "PortWaitResult",
    "ProcessCloseStdinParams",
    "ProcessCloseStdinResult",
    "ProcessHandle",
    "ProcessInfo",
    "ProcessInspectParams",
    "ProcessInspectResult",
    "ProcessKillParams",
    "ProcessKillResult",
    "ProcessOutputSnapshot",
    "ProcessPhase",
    "ProcessReadOutputParams",
    "ProcessReadOutputResult",
    "ProcessReleaseParams",
    "ProcessReleaseResult",
    "ProcessSignal",
    "ProcessSignalParams",
    "ProcessSignalResult",
    "ProcessStartParams",
    "ProcessStartResult",
    "ProcessStatus",
    "ProcessStream",
    "ProcessStreamRead",
    "ProcessStreamSnapshot",
    "ProcessWaitCondition",
    "ProcessWaitParams",
    "ProcessWaitResult",
    "ProcessWriteStdinParams",
    "ProcessWriteStdinResult",
    "ReceiptGetParams",
    "ReceiptGetResult",
    "ReceiptOutcome",
    "ReceiptRef",
    "ReceiptStage",
    "RequestedProcessSignal",
    "RetryHint",
    "SearchMode",
    "SessionCloseParams",
    "SessionCloseResult",
    "ShellCommand",
    "ShellExecParams",
    "ShellExecResult",
    "ShellProfileDescriptor",
    "StructuredOutputDisposition",
    "TerminationReason",
    "WriteMode",
]
