# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Final, Literal

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, model_validator

from .models import EIPError

EIP_PROTOCOL_VERSION: Final = "1.0"
EIP_PROTOCOL_MAJOR: Final = 1
EIP_PROTOCOL_MINOR: Final = 0
EIP_PROTO_PACKAGE: Final = "converge.agent_envd.eip.v1"
EIP_DESCRIPTOR_SHA256: Final = "eb524fe0af240c7d2ea9ea3cfef6ce5eb2a99e605e3fafc3e102acb698ddbcf4"

type JsonRpcId = StrictStr | StrictInt


class JsonRpcEnvelope(BaseModel):
    model_config = ConfigDict(extra="ignore", frozen=True)

    @model_validator(mode="before")
    @classmethod
    def _reject_reserved_extensions(cls, value: object) -> object:
        if isinstance(value, dict):
            unknown = set(value) - set(cls.model_fields)
            reserved = sorted(name for name in unknown if isinstance(name, str) and name.startswith("eip_"))
            if reserved:
                raise ValueError(f"unknown reserved JSON-RPC field: {reserved[0]}")
        return value


class JsonRpcRequest(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    method: StrictStr
    params: dict[str, object]


class JsonRpcNotification(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    method: StrictStr
    params: dict[str, object]


class JsonRpcSuccessResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    result: dict[str, object]


class JsonRpcErrorResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId | None
    error: EIPError
