# Generated by scripts.eip_codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Final, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, model_validator

from .models import EIPError

EIP_PROTOCOL_VERSION: Final = "1.0"
EIP_PROTOCOL_MAJOR: Final = 1
EIP_PROTOCOL_MINOR: Final = 0
EIP_PROTO_PACKAGE: Final = "converge.agent_envd.eip.v1"
EIP_DESCRIPTOR_SHA256: Final = "a1cac18f08fa45ae57816765ba1fc328ab9f66b91e49cf6d49d84e6ff835a723"

type JsonRpcId = StrictStr | Annotated[StrictInt, Field(ge=-(2**63), le=2**63 - 1)]


class JsonRpcEnvelope(BaseModel):
    model_config = ConfigDict(extra="ignore", frozen=True)

    @model_validator(mode="before")
    @classmethod
    def _reject_reserved_extensions(cls, value: object) -> object:
        if isinstance(value, dict):
            unknown = set(value) - set(cls.model_fields)
            reserved = sorted(name for name in unknown if isinstance(name, str) and name.startswith("eip_"))
            if reserved:
                raise ValueError(f"unknown reserved JSON-RPC field: {reserved[0]}")
        return value


class JsonRpcRequest(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    method: StrictStr
    params: dict[str, object]


class JsonRpcSuccessResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    result: dict[str, object]


class JsonRpcErrorResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId | None
    error: EIPError
