"""usage facts and bigint resource versions

Revision ID: 9927a13036d0
Revises: afe52d35d0ec
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "9927a13036d0"
down_revision = "afe52d35d0ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("run_attempt_id", sa.String(), nullable=False),
        sa.Column("harness_run_id", sa.String(), nullable=False),
        sa.Column("call_id", sa.String(), nullable=True),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_id", sa.String(length=72), nullable=True),
        sa.Column("price_snapshot", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], name=op.f("fk_usage_records_model_id_models")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_usage_records_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_usage_records_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "run_attempt_id"],
            ["run_attempts.run_id", "run_attempts.id"],
            name=op.f("fk_usage_records_run_id_run_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "run_id"],
            ["runs.workspace_id", "runs.id"],
            name=op.f("fk_usage_records_workspace_id_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.alter_column(
        "agents",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "api_keys",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "model_providers",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "models",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "organizations",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "principals",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "runs",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "sessions",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "threads",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "workspaces",
        "version",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER usage_immutable BEFORE UPDATE OR DELETE ON usage_records FOR EACH ROW EXECUTE FUNCTION refuse_execution_fact_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER usage_immutable ON usage_records")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workspaces",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "threads",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "sessions",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "runs",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "principals",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "organizations",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "models",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "model_providers",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "api_keys",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "agents",
        "version",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.drop_table("usage_records")
    # ### end Alembic commands ###
