"""indexed idle thread advancement

Revision ID: d42925a47446
Revises: 9927a13036d0
"""

import sqlalchemy as sa
from alembic import op

revision = "d42925a47446"
down_revision = "9927a13036d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_inbox_pending",
        "inbox_entries",
        ["thread_id", "position"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_threads_idle",
        "threads",
        ["updated_at", "id"],
        unique=False,
        postgresql_where=sa.text("current_run_id IS NULL AND archived_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_threads_idle",
        table_name="threads",
        postgresql_where=sa.text("current_run_id IS NULL AND archived_at IS NULL"),
    )
    op.drop_index("ix_inbox_pending", table_name="inbox_entries", postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
