"""durable run acceptance attempts and lifecycle facts

Revision ID: afe52d35d0ec
Revises: 067bbcaf7053
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "afe52d35d0ec"
down_revision = "067bbcaf7053"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_cursors",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("last_seq", sa.BigInteger(), nullable=False),
        sa.Column("retained_from", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_event_cursors_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_event_cursors_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_event_cursors")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_sessions_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_sessions_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_sessions_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_sessions_workspace_id_id")),
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("origin_thread_id", sa.String(), nullable=True),
        sa.Column("origin_run_id", sa.String(), nullable=True),
        sa.Column("origin_tool_call_id", sa.String(), nullable=True),
        sa.Column("current_run_id", sa.String(length=72), nullable=True),
        sa.Column("head_run_id", sa.String(length=72), nullable=True),
        sa.Column("last_run_id", sa.String(length=72), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(origin = 'new' AND origin_thread_id IS NULL AND origin_run_id IS NULL AND origin_tool_call_id IS NULL) OR (origin = 'fork' AND origin_thread_id IS NOT NULL AND origin_run_id IS NOT NULL AND origin_tool_call_id IS NULL) OR (origin = 'child' AND origin_thread_id IS NOT NULL AND origin_run_id IS NOT NULL AND origin_tool_call_id IS NOT NULL)",
            name=op.f("ck_threads_origin_links"),
        ),
        sa.CheckConstraint("origin IN ('new','fork','child')", name=op.f("ck_threads_origin")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_threads_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_threads_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "session_id", "origin_thread_id"],
            ["threads.workspace_id", "threads.session_id", "threads.id"],
            name="fk_threads_origin_thread",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "session_id"],
            ["sessions.workspace_id", "sessions.id"],
            name=op.f("fk_threads_workspace_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threads")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_threads_workspace_id_id")),
        sa.UniqueConstraint("workspace_id", "session_id", "id", name=op.f("uq_threads_workspace_id_session_id_id")),
    )
    op.create_index(
        "uq_threads_child_origin",
        "threads",
        ["origin_run_id", "origin_tool_call_id"],
        unique=True,
        postgresql_where=sa.text("origin = 'child'"),
    )
    op.create_table(
        "inbox_entries",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("delivery", sa.String(), nullable=False),
        sa.Column("position", sa.BigInteger(), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("authority", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("payload_ref", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("agent_revision_id", sa.String(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("waiting_run_id", sa.String(length=72), nullable=True),
        sa.Column("child_run_id", sa.String(length=72), nullable=True),
        sa.Column("origin_run_id", sa.String(length=72), nullable=True),
        sa.Column("request_key", sa.String(), nullable=True),
        sa.Column("request_digest", sa.String(), nullable=True),
        sa.Column("request_kind", sa.String(), nullable=True),
        sa.Column("request_target", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("assigned_run_id", sa.String(), nullable=True),
        sa.Column("incorporated_checkpoint_seq", sa.BigInteger(), nullable=True),
        sa.Column("failure", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kind = 'child_result') = (child_run_id IS NOT NULL AND origin_run_id IS NOT NULL)",
            name=op.f("ck_inbox_entries_child_target"),
        ),
        sa.CheckConstraint(
            "(kind = 'feedback') = (waiting_run_id IS NOT NULL)", name=op.f("ck_inbox_entries_feedback_target")
        ),
        sa.CheckConstraint("(kind = 'message') = (agent_id IS NOT NULL)", name=op.f("ck_inbox_entries_message_agent")),
        sa.CheckConstraint(
            "(status = 'consumed') = (incorporated_checkpoint_seq IS NOT NULL)", name=op.f("ck_inbox_entries_receipt")
        ),
        sa.CheckConstraint("delivery IN ('steer','next_run')", name=op.f("ck_inbox_entries_delivery")),
        sa.CheckConstraint("kind IN ('message','feedback','child_result')", name=op.f("ck_inbox_entries_kind")),
        sa.CheckConstraint("status <> 'pending' OR assigned_run_id IS NULL", name=op.f("ck_inbox_entries_pending")),
        sa.CheckConstraint(
            "status IN ('pending','assigned','consumed','failed','withdrawn')", name=op.f("ck_inbox_entries_status")
        ),
        sa.CheckConstraint(
            "status NOT IN ('assigned','consumed') OR assigned_run_id IS NOT NULL",
            name=op.f("ck_inbox_entries_assignment"),
        ),
        sa.CheckConstraint("(payload IS NULL) <> (payload_ref IS NULL)", name=op.f("ck_inbox_entries_payload")),
        sa.CheckConstraint("position > 0", name=op.f("ck_inbox_entries_position")),
        sa.ForeignKeyConstraint(
            ["agent_id", "agent_revision_id"],
            ["agent_revisions.agent_id", "agent_revisions.id"],
            name=op.f("fk_inbox_entries_agent_id_agent_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_inbox_entries_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_inbox_entries_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"], ["principals.id"], name=op.f("fk_inbox_entries_principal_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.workspace_id", "agents.id"],
            name=op.f("fk_inbox_entries_workspace_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "thread_id"],
            ["threads.workspace_id", "threads.id"],
            name=op.f("fk_inbox_entries_workspace_id_threads"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_entries")),
        sa.UniqueConstraint("thread_id", "id", name=op.f("uq_inbox_entries_thread_id_id")),
        sa.UniqueConstraint(
            "thread_id",
            "position",
            deferrable=True,
            initially="IMMEDIATE",
            name=op.f("uq_inbox_entries_thread_id_position"),
        ),
    )
    op.create_index(
        "uq_inbox_child_result",
        "inbox_entries",
        ["child_run_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'child_result'"),
    )
    op.create_index(
        "uq_inbox_request",
        "inbox_entries",
        ["workspace_id", "principal_id", "request_key"],
        unique=True,
        postgresql_where=sa.text("request_key IS NOT NULL"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("agent_revision_id", sa.String(), nullable=False),
        sa.Column("revision_selection", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("authority", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("environment_mounts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_entry_id", sa.String(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("lineage", sa.String(), nullable=False),
        sa.Column("parent_run_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("wait_reason", sa.String(), nullable=True),
        sa.Column("pending", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_attempt_id", sa.String(length=72), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("max_usage", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("sealed_checkpoint", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("sealed_display", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("output_ref", sa.String(), nullable=True),
        sa.Column("failure", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("usage_at_seal", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lifecycle_seq", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("(lineage = 'root') = (parent_run_id IS NULL)", name=op.f("ck_runs_parent")),
        sa.CheckConstraint("(status = 'running') = (current_attempt_id IS NOT NULL)", name=op.f("ck_runs_attempt")),
        sa.CheckConstraint(
            "(status = 'waiting') = (wait_reason IS NOT NULL AND pending IS NOT NULL)", name=op.f("ck_runs_waiting")
        ),
        sa.CheckConstraint("(status IN ('failed','cancelled')) = (failure IS NOT NULL)", name=op.f("ck_runs_failure")),
        sa.CheckConstraint(
            "(status IN ('waiting','completed')) = (sealed_checkpoint IS NOT NULL)", name=op.f("ck_runs_checkpoint")
        ),
        sa.CheckConstraint(
            "(status IN ('waiting','completed')) = (sealed_display IS NOT NULL)", name=op.f("ck_runs_display")
        ),
        sa.CheckConstraint(
            "(status IN ('waiting','completed','failed','cancelled')) = (sealed_at IS NOT NULL)",
            name=op.f("ck_runs_sealed"),
        ),
        sa.CheckConstraint("lineage IN ('root','continue','fork')", name=op.f("ck_runs_lineage")),
        sa.CheckConstraint(
            "revision_selection IN ('pinned','default','inherited')", name=op.f("ck_runs_revision_selection")
        ),
        sa.CheckConstraint(
            "status IN ('accepted','running','waiting','completed','failed','cancelled')", name=op.f("ck_runs_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('input','queued','feedback','child_result','spawned')", name=op.f("ck_runs_trigger")
        ),
        sa.CheckConstraint(
            "wait_reason IN ('approval','client_tool','user_input','multiple')", name=op.f("ck_runs_wait_reason")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id", "agent_revision_id"],
            ["agent_revisions.agent_id", "agent_revisions.id"],
            name=op.f("fk_runs_agent_id_agent_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_runs_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_runs_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], name=op.f("fk_runs_principal_id_principals")),
        sa.ForeignKeyConstraint(
            ["thread_id", "source_entry_id"],
            ["inbox_entries.thread_id", "inbox_entries.id"],
            name=op.f("fk_runs_thread_id_inbox_entries"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"], ["agents.workspace_id", "agents.id"], name=op.f("fk_runs_workspace_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "session_id", "parent_run_id"],
            ["runs.workspace_id", "runs.session_id", "runs.id"],
            name=op.f("fk_runs_workspace_id_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "session_id", "thread_id"],
            ["threads.workspace_id", "threads.session_id", "threads.id"],
            name=op.f("fk_runs_workspace_id_threads"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("source_entry_id", name=op.f("uq_runs_source_entry_id")),
        sa.UniqueConstraint("thread_id", "id", name=op.f("uq_runs_thread_id_id")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_runs_workspace_id_id")),
        sa.UniqueConstraint("workspace_id", "session_id", "id", name=op.f("uq_runs_workspace_id_session_id_id")),
    )
    op.create_index(
        "ix_runs_due", "runs", ["available_at"], unique=False, postgresql_where=sa.text("status = 'accepted'")
    )
    op.create_index(
        "uq_runs_active_thread",
        "runs",
        ["thread_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('accepted','running')"),
    )
    op.create_table(
        "run_attempts",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("start_reason", sa.String(), nullable=False),
        sa.Column("replaces_attempt_id", sa.String(), nullable=True),
        sa.Column("worker_id", sa.String(), nullable=False),
        sa.Column("worker_build", sa.String(), nullable=False),
        sa.Column("harness_run_id", sa.String(), nullable=True),
        sa.Column("lease_token_hash", sa.String(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("yield_reason", sa.String(), nullable=True),
        sa.Column("failure", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("lifecycle_seq", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status IN ('succeeded','yielded','failed','cancelled')) = (finished_at IS NOT NULL)",
            name=op.f("ck_run_attempts_finished"),
        ),
        sa.CheckConstraint(
            "start_reason IN ('initial','recovery','handoff')", name=op.f("ck_run_attempts_start_reason")
        ),
        sa.CheckConstraint(
            "status IN ('leased','running','succeeded','yielded','failed','cancelled')",
            name=op.f("ck_run_attempts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_run_attempts_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_run_attempts_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "replaces_attempt_id"],
            ["run_attempts.run_id", "run_attempts.id"],
            name=op.f("fk_run_attempts_run_id_run_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "run_id"], ["runs.workspace_id", "runs.id"], name=op.f("fk_run_attempts_workspace_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_attempts")),
        sa.UniqueConstraint("run_id", "id", name=op.f("uq_run_attempts_run_id_id")),
        sa.UniqueConstraint("run_id", "number", name=op.f("uq_run_attempts_run_id_number")),
    )
    op.create_index(
        "ix_attempts_expiry",
        "run_attempts",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('leased','running')"),
    )
    op.create_index(
        "uq_attempts_live_run",
        "run_attempts",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('leased','running')"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("entity_kind", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("entity_seq", sa.BigInteger(), nullable=False),
        sa.Column("mutation_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("run_attempt_id", sa.String(), nullable=True),
        sa.Column("actor_id", sa.String(length=72), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('run.accepted','run.running','run.waiting','run.completed','run.failed','run.cancelled','run_attempt.leased','run_attempt.running','run_attempt.succeeded','run_attempt.yielded','run_attempt.failed','run_attempt.cancelled')",
            name=op.f("ck_events_kind"),
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["principals.id"], name=op.f("fk_events_actor_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_events_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_events_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "run_attempt_id"],
            ["run_attempts.run_id", "run_attempts.id"],
            name=op.f("fk_events_run_id_run_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "run_id"], ["runs.workspace_id", "runs.id"], name=op.f("fk_events_workspace_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "session_id"],
            ["sessions.workspace_id", "sessions.id"],
            name=op.f("fk_events_workspace_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "thread_id"],
            ["threads.workspace_id", "threads.id"],
            name=op.f("fk_events_workspace_id_threads"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "entity_kind", "entity_id", "entity_seq", name=op.f("uq_events_entity_kind_entity_id_entity_seq")
        ),
        sa.UniqueConstraint("workspace_id", "seq", name=op.f("uq_events_workspace_id_seq")),
    )
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fk_threads_current_run",
        "threads",
        "runs",
        ["id", "current_run_id"],
        ["thread_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_threads_head_run",
        "threads",
        "runs",
        ["id", "head_run_id"],
        ["thread_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_threads_last_run",
        "threads",
        "runs",
        ["id", "last_run_id"],
        ["thread_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_threads_origin_run",
        "threads",
        "runs",
        ["workspace_id", "session_id", "origin_run_id"],
        ["workspace_id", "session_id", "id"],
    )
    op.create_foreign_key("fk_inbox_entries_child_run_id_runs", "inbox_entries", "runs", ["child_run_id"], ["id"])
    op.create_foreign_key("fk_inbox_entries_origin_run_id_runs", "inbox_entries", "runs", ["origin_run_id"], ["id"])
    op.create_foreign_key(
        "fk_inbox_assigned_run",
        "inbox_entries",
        "runs",
        ["thread_id", "assigned_run_id"],
        ["thread_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key("fk_inbox_entries_waiting_run_id_runs", "inbox_entries", "runs", ["waiting_run_id"], ["id"])
    op.create_foreign_key(
        "fk_runs_current_attempt",
        "runs",
        "run_attempts",
        ["id", "current_attempt_id"],
        ["run_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )

    for table in ("sessions", "threads", "runs"):
        op.execute(
            f"CREATE TRIGGER stamp_resource BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION stamp_resource()"
        )
    op.execute("""
        CREATE FUNCTION guard_run_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status IN ('waiting','completed','failed','cancelled') THEN
                IF (to_jsonb(NEW) - ARRAY['labels','version','updated_at']) IS DISTINCT FROM
                   (to_jsonb(OLD) - ARRAY['labels','version','updated_at'])
                THEN RAISE EXCEPTION 'terminal run facts are immutable'; END IF;
                RETURN NEW;
            END IF;
            IF (to_jsonb(NEW) - ARRAY['status','wait_reason','pending','cancel_requested_at','current_attempt_id','available_at','attempts','sealed_checkpoint','sealed_display','output','output_ref','failure','usage_at_seal','labels','lifecycle_seq','started_at','sealed_at','updated_at','version']) IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['status','wait_reason','pending','cancel_requested_at','current_attempt_id','available_at','attempts','sealed_checkpoint','sealed_display','output','output_ref','failure','usage_at_seal','labels','lifecycle_seq','started_at','sealed_at','updated_at','version'])
            THEN RAISE EXCEPTION 'accepted run selection is immutable'; END IF;
            IF NEW.status <> OLD.status AND NOT (
                (OLD.status = 'accepted' AND NEW.status IN ('running','failed','cancelled')) OR
                (OLD.status = 'running' AND NEW.status IN ('accepted','waiting','completed','failed','cancelled'))
            ) THEN RAISE EXCEPTION 'invalid run transition'; END IF;
            RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER guard_run_mutation BEFORE UPDATE ON runs FOR EACH ROW EXECUTE FUNCTION guard_run_mutation()"
    )
    op.execute("""
        CREATE FUNCTION guard_attempt_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status IN ('succeeded','yielded','failed','cancelled')
            THEN RAISE EXCEPTION 'terminal attempt is immutable'; END IF;
            IF (to_jsonb(NEW) - ARRAY['status','harness_run_id','lease_expires_at','heartbeat_at','yield_reason','failure','lifecycle_seq','started_at','finished_at','updated_at']) IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['status','harness_run_id','lease_expires_at','heartbeat_at','yield_reason','failure','lifecycle_seq','started_at','finished_at','updated_at'])
               OR (OLD.harness_run_id IS NOT NULL AND NEW.harness_run_id IS DISTINCT FROM OLD.harness_run_id)
            THEN RAISE EXCEPTION 'attempt identity is immutable'; END IF;
            IF OLD.status = 'running' AND NEW.status = 'leased'
            THEN RAISE EXCEPTION 'invalid attempt transition'; END IF;
            IF NEW.lease_expires_at > OLD.lease_expires_at AND OLD.lease_expires_at <= clock_timestamp()
            THEN RAISE EXCEPTION 'expired lease cannot be revived'; END IF;
            NEW.updated_at = clock_timestamp();
            RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER guard_attempt_mutation BEFORE UPDATE ON run_attempts FOR EACH ROW EXECUTE FUNCTION guard_attempt_mutation()"
    )
    op.execute("""
        CREATE FUNCTION guard_input_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF ROW(NEW.id,NEW.organization_id,NEW.workspace_id,NEW.thread_id,NEW.kind,NEW.principal_id,NEW.authority,NEW.request_key,NEW.request_digest,NEW.request_kind,NEW.request_target,NEW.created_at)
               IS DISTINCT FROM ROW(OLD.id,OLD.organization_id,OLD.workspace_id,OLD.thread_id,OLD.kind,OLD.principal_id,OLD.authority,OLD.request_key,OLD.request_digest,OLD.request_kind,OLD.request_target,OLD.created_at)
            THEN RAISE EXCEPTION 'input identity and replay evidence are immutable'; END IF;
            IF OLD.status IN ('consumed','failed','withdrawn')
            THEN RAISE EXCEPTION 'settled input is immutable'; END IF;
            IF OLD.status = 'assigned' AND (
                (to_jsonb(NEW) - ARRAY['status','assigned_run_id','incorporated_checkpoint_seq','failure','finished_at']) IS DISTINCT FROM
                (to_jsonb(OLD) - ARRAY['status','assigned_run_id','incorporated_checkpoint_seq','failure','finished_at']) OR
                (NEW.status <> 'pending' AND NEW.assigned_run_id IS DISTINCT FROM OLD.assigned_run_id)
            ) THEN RAISE EXCEPTION 'assigned input is immutable'; END IF;
            IF NEW.status <> OLD.status AND NOT (
                (OLD.status = 'pending' AND NEW.status IN ('assigned','failed','withdrawn')) OR
                (OLD.status = 'assigned' AND NEW.status IN ('pending','consumed','failed'))
            ) THEN RAISE EXCEPTION 'invalid input transition'; END IF;
            RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER guard_input_mutation BEFORE UPDATE ON inbox_entries FOR EACH ROW EXECUTE FUNCTION guard_input_mutation()"
    )
    op.execute("""
        CREATE FUNCTION refuse_execution_fact_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'execution fact is immutable'; END $$
    """)
    op.execute(
        "CREATE TRIGGER event_immutable BEFORE UPDATE OR DELETE ON events FOR EACH ROW EXECUTE FUNCTION refuse_execution_fact_mutation()"
    )
    op.execute("""
        CREATE FUNCTION check_thread_run_links() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE t threads; target text;
        BEGIN
            IF TG_TABLE_NAME = 'threads' THEN target = NEW.id; ELSE target = NEW.thread_id; END IF;
            SELECT * INTO t FROM threads WHERE id = target;
            IF t.current_run_id IS DISTINCT FROM (SELECT id FROM runs WHERE thread_id = target AND status IN ('accepted','running'))
                OR (t.head_run_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM runs WHERE id=t.head_run_id AND status IN ('completed','waiting')))
                OR (t.last_run_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM runs WHERE id=t.last_run_id AND status IN ('completed','waiting','failed','cancelled')))
            THEN RAISE EXCEPTION 'thread run pointer/status mismatch'; END IF;
            RETURN NULL;
        END $$
    """)
    for table in ("threads", "runs"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER check_thread_run_links AFTER INSERT OR UPDATE ON {table} DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_thread_run_links()"
        )
    op.execute("""
        CREATE FUNCTION check_attempt_run_links() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE r runs; target text;
        BEGIN
            IF TG_TABLE_NAME = 'runs' THEN target=NEW.id; ELSE target=NEW.run_id; END IF;
            SELECT * INTO r FROM runs WHERE id=target;
            IF r.current_attempt_id IS DISTINCT FROM (SELECT id FROM run_attempts WHERE run_id=target AND status IN ('leased','running'))
            THEN RAISE EXCEPTION 'run attempt pointer/status mismatch'; END IF;
            RETURN NULL;
        END $$
    """)
    for table in ("runs", "run_attempts"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER check_attempt_run_links AFTER INSERT OR UPDATE ON {table} DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_attempt_run_links()"
        )


def downgrade() -> None:
    for table in ("runs", "run_attempts"):
        op.execute(f"DROP TRIGGER check_attempt_run_links ON {table}")
    op.execute("DROP FUNCTION check_attempt_run_links()")
    for table in ("threads", "runs"):
        op.execute(f"DROP TRIGGER check_thread_run_links ON {table}")
    op.execute("DROP FUNCTION check_thread_run_links()")
    op.execute("DROP TRIGGER event_immutable ON events")
    op.execute("DROP FUNCTION refuse_execution_fact_mutation()")
    for table, function in (
        ("runs", "guard_run_mutation"),
        ("run_attempts", "guard_attempt_mutation"),
        ("inbox_entries", "guard_input_mutation"),
    ):
        op.execute(f"DROP TRIGGER {function} ON {table}")
        op.execute(f"DROP FUNCTION {function}()")
    for table in ("sessions", "threads", "runs"):
        op.execute(f"DROP TRIGGER stamp_resource ON {table}")
    op.drop_constraint("fk_threads_current_run", "threads", type_="foreignkey")
    op.drop_constraint("fk_threads_head_run", "threads", type_="foreignkey")
    op.drop_constraint("fk_threads_last_run", "threads", type_="foreignkey")
    op.drop_constraint("fk_threads_origin_run", "threads", type_="foreignkey")
    op.drop_constraint("fk_inbox_entries_child_run_id_runs", "inbox_entries", type_="foreignkey")
    op.drop_constraint("fk_inbox_entries_origin_run_id_runs", "inbox_entries", type_="foreignkey")
    op.drop_constraint("fk_inbox_assigned_run", "inbox_entries", type_="foreignkey")
    op.drop_constraint("fk_inbox_entries_waiting_run_id_runs", "inbox_entries", type_="foreignkey")
    op.drop_constraint("fk_runs_current_attempt", "runs", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_index(
        "uq_attempts_live_run", table_name="run_attempts", postgresql_where=sa.text("status IN ('leased','running')")
    )
    op.drop_index(
        "ix_attempts_expiry", table_name="run_attempts", postgresql_where=sa.text("status IN ('leased','running')")
    )
    op.drop_table("run_attempts")
    op.drop_index(
        "uq_runs_active_thread", table_name="runs", postgresql_where=sa.text("status IN ('accepted','running')")
    )
    op.drop_index("ix_runs_due", table_name="runs", postgresql_where=sa.text("status = 'accepted'"))
    op.drop_table("runs")
    op.drop_index("uq_inbox_request", table_name="inbox_entries", postgresql_where=sa.text("request_key IS NOT NULL"))
    op.drop_index(
        "uq_inbox_child_result", table_name="inbox_entries", postgresql_where=sa.text("kind = 'child_result'")
    )
    op.drop_table("inbox_entries")
    op.drop_index("uq_threads_child_origin", table_name="threads", postgresql_where=sa.text("origin = 'child'"))
    op.drop_table("threads")
    op.drop_table("sessions")
    op.drop_table("event_cursors")
    # ### end Alembic commands ###
