"""credentials and explicit account audit scope

Revision ID: 3b14eb54cd65
Revises: 3c88556f40aa
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "3b14eb54cd65"
down_revision = "3c88556f40aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_api_keys_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_api_keys_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_api_keys_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], name=op.f("fk_api_keys_principal_id_principals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("secret_hash", name=op.f("uq_api_keys_secret_hash")),
    )
    op.create_index(op.f("ix_api_keys_principal_id"), "api_keys", ["principal_id"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('session','password_reset','email_change')", name=op.f("ck_tokens_kind")),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], name=op.f("fk_tokens_principal_id_principals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
        sa.UniqueConstraint("secret_hash", name=op.f("uq_tokens_secret_hash")),
    )
    op.create_index(op.f("ix_tokens_expires_at"), "tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_tokens_principal_id"), "tokens", ["principal_id"], unique=False)
    op.alter_column("audit_events", "organization_id", existing_type=sa.VARCHAR(length=72), nullable=True)
    op.create_check_constraint(
        op.f("ck_audit_events_global_scope"), "audit_events", "organization_id IS NOT NULL OR workspace_id IS NULL"
    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE FUNCTION guard_credential() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (to_jsonb(NEW) - ARRAY['version','updated_at','name','expires_at','last_used_at','revoked_at'])
                 IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['version','updated_at','name','expires_at','last_used_at','revoked_at'])
               OR (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at)
            THEN RAISE EXCEPTION 'credential identity and confinement are immutable'; END IF;
            RETURN NEW;
        END $$
    """)
    for table in ("api_keys", "tokens"):
        op.execute(
            f"CREATE TRIGGER guard_credential BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_credential()"
        )
    op.execute("CREATE TRIGGER stamp_resource BEFORE UPDATE ON api_keys FOR EACH ROW EXECUTE FUNCTION stamp_resource()")


def downgrade() -> None:
    op.execute("DROP TRIGGER stamp_resource ON api_keys")
    for table in ("api_keys", "tokens"):
        op.execute(f"DROP TRIGGER guard_credential ON {table}")
    op.execute("DROP FUNCTION guard_credential()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_audit_events_global_scope"), "audit_events", type_="check")
    op.alter_column("audit_events", "organization_id", existing_type=sa.VARCHAR(length=72), nullable=False)
    op.drop_index(op.f("ix_tokens_principal_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_expires_at"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_api_keys_principal_id"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
