"""model configuration and immutable agent revisions

Revision ID: 067bbcaf7053
Revises: 3b14eb54cd65
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "067bbcaf7053"
down_revision = "3b14eb54cd65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("default_revision_id", sa.String(length=72), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source IN ('custom', 'builtin')", name=op.f("ck_agents_source")),
        sa.ForeignKeyConstraint(["created_by_id"], ["principals.id"], name=op.f("fk_agents_created_by_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_agents_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_agents_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["updated_by_id"], ["principals.id"], name=op.f("fk_agents_updated_by_id_principals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_agents_workspace_id_id")),
        sa.UniqueConstraint("workspace_id", "key", name=op.f("uq_agents_workspace_id_key")),
    )
    op.create_table(
        "model_providers",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_model_providers_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_model_providers_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_model_providers_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["principals.id"], name=op.f("fk_model_providers_updated_by_id_principals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_providers")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_model_providers_organization_id_id")),
    )
    op.create_table(
        "agent_revisions",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("number > 0", name=op.f("ck_agent_revisions_number")),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["principals.id"], name=op.f("fk_agent_revisions_created_by_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_agent_revisions_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_agent_revisions_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.workspace_id", "agents.id"],
            name=op.f("fk_agent_revisions_workspace_id_agents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_revisions")),
        sa.UniqueConstraint("agent_id", "id", name=op.f("uq_agent_revisions_agent_id_id")),
        sa.UniqueConstraint("agent_id", "number", name=op.f("uq_agent_revisions_agent_id_number")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_agent_revisions_workspace_id_id")),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("updated_by_id", sa.String(length=72), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["principals.id"], name=op.f("fk_models_created_by_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "provider_id"],
            ["model_providers.organization_id", "model_providers.id"],
            name=op.f("fk_models_organization_id_model_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_models_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_models_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["updated_by_id"], ["principals.id"], name=op.f("fk_models_updated_by_id_principals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_models_organization_id_id")),
        sa.UniqueConstraint("provider_id", "key", name=op.f("uq_models_provider_id_key")),
    )
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fk_agents_default_revision",
        "agents",
        "agent_revisions",
        ["id", "default_revision_id"],
        ["agent_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )
    for table in ("agents", "model_providers", "models"):
        op.execute(
            f"CREATE TRIGGER stamp_resource BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION stamp_resource()"
        )
    op.execute("""
        CREATE FUNCTION refuse_revision_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'resource revision is immutable'; END $$
    """)
    op.execute(
        "CREATE TRIGGER revision_immutable BEFORE UPDATE OR DELETE ON agent_revisions FOR EACH ROW EXECUTE FUNCTION refuse_revision_mutation()"
    )
    op.execute("""
        CREATE FUNCTION guard_resource_identity() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF ROW(NEW.id, NEW.organization_id, NEW.workspace_id, NEW.created_by_id, NEW.created_at)
                IS DISTINCT FROM ROW(OLD.id, OLD.organization_id, OLD.workspace_id, OLD.created_by_id, OLD.created_at)
            THEN RAISE EXCEPTION 'resource identity and scope are immutable'; END IF;
            RETURN NEW;
        END $$
    """)
    for table in ("agents", "model_providers", "models"):
        op.execute(
            f"CREATE TRIGGER guard_resource_identity BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_resource_identity()"
        )
    op.execute("""
        CREATE FUNCTION guard_model_provider_scope() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM model_providers p WHERE p.id = NEW.provider_id
                AND p.organization_id = NEW.organization_id
                AND (p.workspace_id IS NULL OR p.workspace_id = NEW.workspace_id)
            ) THEN RAISE EXCEPTION 'model provider scope mismatch'; END IF;
            RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER guard_model_provider_scope BEFORE INSERT OR UPDATE ON models FOR EACH ROW EXECUTE FUNCTION guard_model_provider_scope()"
    )


def downgrade() -> None:
    op.drop_constraint("fk_agents_default_revision", "agents", type_="foreignkey")
    op.execute("DROP TRIGGER guard_model_provider_scope ON models")
    op.execute("DROP FUNCTION guard_model_provider_scope()")
    for table in ("agents", "model_providers", "models"):
        op.execute(f"DROP TRIGGER guard_resource_identity ON {table}")
        op.execute(f"DROP TRIGGER stamp_resource ON {table}")
    op.execute("DROP FUNCTION guard_resource_identity()")
    op.execute("DROP TRIGGER revision_immutable ON agent_revisions")
    op.execute("DROP FUNCTION refuse_revision_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("models")
    op.drop_table("agent_revisions")
    op.drop_table("model_providers")
    op.drop_table("agents")
    # ### end Alembic commands ###
