"""session activity and bounded navigation

Revision ID: 9c172cfae8e8
Revises: 611cf188440e
"""

from alembic import op

revision = "9c172cfae8e8"
down_revision = "611cf188440e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_runs_workspace_session_created", "runs", ["workspace_id", "session_id", "created_at", "id"], unique=False
    )
    op.create_index("ix_sessions_workspace_activity", "sessions", ["workspace_id", "updated_at", "id"], unique=False)
    # ### end Alembic commands ###
    op.execute("DROP TRIGGER stamp_resource ON sessions")
    op.execute("""
        CREATE FUNCTION stamp_session() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF (to_jsonb(NEW) - ARRAY['version', 'updated_at'])
                IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['version', 'updated_at']) THEN
                NEW.version := OLD.version + 1;
                NEW.updated_at := GREATEST(OLD.updated_at, clock_timestamp());
            ELSE
                NEW.version := OLD.version;
                NEW.updated_at := GREATEST(OLD.updated_at, NEW.updated_at);
            END IF;
            RETURN NEW;
        END $$
    """)
    op.execute("CREATE TRIGGER stamp_session BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION stamp_session()")


def downgrade() -> None:
    op.execute("DROP TRIGGER stamp_session ON sessions")
    op.execute("DROP FUNCTION stamp_session()")
    op.execute("CREATE TRIGGER stamp_resource BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION stamp_resource()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sessions_workspace_activity", table_name="sessions")
    op.drop_index("ix_runs_workspace_session_created", table_name="runs")
    # ### end Alembic commands ###
