"""bootstrap tenancy foundation

Revision ID: 3c88556f40aa
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "3c88556f40aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("key", name=op.f("uq_organizations_key")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_workspaces_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_workspaces_organization_id_id")),
        sa.UniqueConstraint("organization_id", "key", name=op.f("uq_workspaces_organization_id_key")),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("home_workspace_id", sa.String(length=72), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(kind = 'service_account') = (home_workspace_id IS NOT NULL)", name=op.f("ck_principals_account_home")
        ),
        sa.CheckConstraint("(kind = 'user') = (email IS NOT NULL)", name=op.f("ck_principals_user_email")),
        sa.CheckConstraint("kind IN ('user', 'service_account')", name=op.f("ck_principals_kind")),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_principals_status")),
        sa.ForeignKeyConstraint(
            ["home_workspace_id"], ["workspaces.id"], name=op.f("fk_principals_home_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
        sa.UniqueConstraint("email", name=op.f("uq_principals_email")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("actor_id", sa.String(length=72), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("outcome IN ('ok', 'denied', 'failed')", name=op.f("ck_audit_events_outcome")),
        sa.ForeignKeyConstraint(["actor_id"], ["principals.id"], name=op.f("fk_audit_events_actor_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_audit_events_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_audit_events_organization_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_table(
        "grants",
        sa.Column("id", sa.String(length=72), nullable=False),
        sa.Column("organization_id", sa.String(length=72), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(length=72), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["principals.id"], name=op.f("fk_grants_created_by_id_principals")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
            name=op.f("fk_grants_organization_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name=op.f("fk_grants_organization_id_organizations")
        ),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], name=op.f("fk_grants_principal_id_principals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grants")),
    )
    op.create_index(
        "uq_grants_scope",
        "grants",
        ["principal_id", "organization_id", sa.literal_column("COALESCE(workspace_id, '')")],
        unique=True,
    )
    op.create_table(
        "passwords",
        sa.Column("principal_id", sa.String(length=72), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], name=op.f("fk_passwords_principal_id_principals")),
        sa.PrimaryKeyConstraint("principal_id", name=op.f("pk_passwords")),
    )
    # ### end Alembic commands ###

    # Mutable-resource versions advance at the database boundary, including raw SQL.
    op.execute("""
        CREATE FUNCTION stamp_resource() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            NEW.version := OLD.version + 1;
            NEW.updated_at := clock_timestamp();
            RETURN NEW;
        END $$
    """)
    for table in ("organizations", "workspaces", "principals"):
        op.execute(
            f"CREATE TRIGGER stamp_resource BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION stamp_resource()"
        )
    op.execute("""
        CREATE FUNCTION refuse_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit events are immutable';
        END $$
    """)
    op.execute(
        "CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION refuse_audit_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER audit_immutable ON audit_events")
    op.execute("DROP FUNCTION refuse_audit_mutation()")
    for table in ("organizations", "workspaces", "principals"):
        op.execute(f"DROP TRIGGER stamp_resource ON {table}")
    op.execute("DROP FUNCTION stamp_resource()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passwords")
    op.drop_index("uq_grants_scope", table_name="grants")
    op.drop_table("grants")
    op.drop_table("audit_events")
    op.drop_table("principals")
    op.drop_table("workspaces")
    op.drop_table("organizations")
    # ### end Alembic commands ###
