from __future__ import annotations

from typing import Protocol


class EIPTransport(Protocol):
    async def send(self, payload: bytes) -> None: ...

    async def receive(self) -> bytes: ...

    async def close(self) -> None: ...

    def set_limits(self, *, max_request_bytes: int, max_response_bytes: int) -> None: ...
