from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from google.protobuf import descriptor_pb2

from .model import OptionReader, SchemaIndex, real_oneofs, short_name, topological_messages

GENERATED_HEADER = "# Generated by scripts.eip_codegen. DO NOT EDIT.\n"
TOOLING_MESSAGES = {"EIPMethodOptions", "EIPMessageOptions", "EIPEnumValueOptions", "EIPFieldOptions"}
TOOLING_ENUMS = {"MethodKind", "IdempotencyClass", "IdempotencyKeyMode", "ErrorFamily", "EIPStringFormat"}
NO_REBUILD_MODELS = {
    "ProcessHandle",
    "OutputReference",
    "OutputCursor",
    "ReceiptRef",
    "FileRevision",
}


def _snake_upper(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def _enum_values(enum: descriptor_pb2.EnumDescriptorProto, options: OptionReader) -> list[tuple[str, str]]:
    prefix = f"{_snake_upper(enum.name)}_"
    values: list[tuple[str, str]] = []
    for value in enum.value:
        option = options.enum_value(value)
        if option is None or not option.json_name:
            continue
        member = value.name.removeprefix(prefix)
        values.append((member, option.json_name))
    return values


def _error_code_values(
    enum: descriptor_pb2.EnumDescriptorProto,
    options: OptionReader,
) -> list[tuple[str, str, int]]:
    prefix = f"{_snake_upper(enum.name)}_"
    values: list[tuple[str, str, int]] = []
    codes: set[int] = set()
    for value in enum.value:
        option = options.enum_value(value)
        if option is None or not option.json_name:
            continue
        if not option.HasField("error_code"):
            raise ValueError(f"EIP error type {value.name} has no JSON-RPC code")
        if option.error_code in codes:
            raise ValueError(f"duplicate EIP JSON-RPC error code: {option.error_code}")
        codes.add(option.error_code)
        member = value.name.removeprefix(prefix)
        values.append((member, option.json_name, option.error_code))
    return values


def _field_option(field: descriptor_pb2.FieldDescriptorProto, options: OptionReader) -> Any | None:
    return options.field(field)


def _base_field_type(
    field: descriptor_pb2.FieldDescriptorProto,
    index: SchemaIndex,
    options: OptionReader,
) -> str:
    field_option = _field_option(field, options)
    if field.type == descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE:
        if field.type_name == ".google.protobuf.Timestamp":
            return "EIPTimestamp"
        if field.type_name == ".google.protobuf.Value":
            return "JsonValue"
        if field.type_name in index.map_entries:
            entry = index.map_entries[field.type_name]
            key_type = _base_field_type(entry.field[0], index, options)
            value_type = _base_field_type(entry.field[1], index, options)
            return f"dict[{key_type}, {value_type}]"
        return short_name(field.type_name)
    if field.type == descriptor_pb2.FieldDescriptorProto.TYPE_ENUM:
        return short_name(field.type_name)
    if field.type == descriptor_pb2.FieldDescriptorProto.TYPE_STRING:
        if field_option is not None and field_option.HasField("const_string"):
            return f"Literal[{field_option.const_string!r}]"
        if field_option is not None:
            format_name = options.enum_name("EIPStringFormat", field_option.string_format)
            if format_name == "EIP_STRING_FORMAT_IDENTIFIER":
                return "Identifier"
            if format_name == "EIP_STRING_FORMAT_PATH":
                return "AbsoluteEIPPath"
            if format_name == "EIP_STRING_FORMAT_BASE64_UNPADDED":
                return "Base64Unpadded"
            if format_name == "EIP_STRING_FORMAT_PROTOCOL_VERSION":
                return "ProtocolVersion"
        return "StrictStr"
    if field.type == descriptor_pb2.FieldDescriptorProto.TYPE_BOOL:
        if field_option is not None and field_option.HasField("const_bool"):
            return f"Literal[{field_option.const_bool!r}]"
        return "StrictBool"
    if field.type in {
        descriptor_pb2.FieldDescriptorProto.TYPE_UINT32,
        descriptor_pb2.FieldDescriptorProto.TYPE_UINT64,
        descriptor_pb2.FieldDescriptorProto.TYPE_FIXED32,
        descriptor_pb2.FieldDescriptorProto.TYPE_FIXED64,
    }:
        minimum = 0
        maximum = (
            2**32 - 1
            if field.type
            in {
                descriptor_pb2.FieldDescriptorProto.TYPE_UINT32,
                descriptor_pb2.FieldDescriptorProto.TYPE_FIXED32,
            }
            else 2**64 - 1
        )
        if field_option is not None:
            if field_option.HasField("minimum"):
                minimum = field_option.minimum
            if field_option.HasField("maximum"):
                maximum = min(maximum, field_option.maximum)
        return f"Annotated[StrictInt, Field(ge={minimum}, le={maximum})]"
    if field.type in {
        descriptor_pb2.FieldDescriptorProto.TYPE_INT32,
        descriptor_pb2.FieldDescriptorProto.TYPE_INT64,
        descriptor_pb2.FieldDescriptorProto.TYPE_SINT32,
        descriptor_pb2.FieldDescriptorProto.TYPE_SINT64,
        descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED32,
        descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED64,
    }:
        bits = (
            32
            if field.type
            in {
                descriptor_pb2.FieldDescriptorProto.TYPE_INT32,
                descriptor_pb2.FieldDescriptorProto.TYPE_SINT32,
                descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED32,
            }
            else 64
        )
        return f"Annotated[StrictInt, Field(ge={-(2 ** (bits - 1))}, le={2 ** (bits - 1) - 1})]"
    if field.type in {descriptor_pb2.FieldDescriptorProto.TYPE_FLOAT, descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE}:
        return "StrictFloat"
    raise ValueError(f"unsupported field type for {field.name}: {field.type}")


def _field_annotation(
    field: descriptor_pb2.FieldDescriptorProto,
    message: descriptor_pb2.DescriptorProto,
    index: SchemaIndex,
    options: OptionReader,
) -> tuple[str, str | None]:
    base_type = _base_field_type(field, index, options)
    is_map = field.type_name in index.map_entries
    if field.label == descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED and not is_map:
        field_option = _field_option(field, options)
        annotation = f"tuple[{base_type}, ...]"
        if field_option is not None and field_option.HasField("min_length") and field_option.min_length > 0:
            return f"Annotated[{annotation}, Field(min_length={field_option.min_length})]", None
        return annotation, "()"
    if is_map:
        return base_type, "Field(default_factory=dict)"

    field_option = _field_option(field, options)
    if field_option is not None:
        if field_option.HasField("default_bool"):
            return base_type, repr(field_option.default_bool)
        if field_option.HasField("default_uint"):
            return base_type, repr(field_option.default_uint)
        if field_option.HasField("default_string"):
            if field.type == descriptor_pb2.FieldDescriptorProto.TYPE_ENUM:
                return base_type, f"{base_type}({field_option.default_string!r})"
            return base_type, repr(field_option.default_string)
        if field_option.default_message:
            return base_type, f"Field(default_factory={base_type})"

    oneofs = real_oneofs(message)
    in_real_oneof = field.HasField("oneof_index") and field.oneof_index in oneofs
    if field.proto3_optional or in_real_oneof:
        return f"{base_type} | None", "None"
    return base_type, None


def render_models(index: SchemaIndex, options: OptionReader) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "import base64",
        "import binascii",
        "import re",
        "from datetime import datetime, timezone",
        "from enum import StrEnum",
        "from types import MappingProxyType",
        "from typing import Annotated, Final, Literal, Mapping",
        "",
        "from pydantic import (",
        "    AfterValidator,",
        "    BaseModel,",
        "    BeforeValidator,",
        "    ConfigDict,",
        "    Field,",
        "    JsonValue,",
        "    RootModel,",
        "    StrictBool,",
        "    StrictFloat,",
        "    StrictInt,",
        "    StrictStr,",
        "    model_validator,",
        ")",
        "",
        "",
        "def _validate_absolute_eip_path(value: str) -> str:",
        "    if not value.startswith('/') or '\\x00' in value:",
        "        raise ValueError('EIP paths must be absolute UTF-8 paths without NUL')",
        "    if value != '/' and (",
        "        value.endswith('/')",
        "        or any(part in {'', '.', '..'} for part in value.split('/')[1:])",
        "    ):",
        "        raise ValueError('EIP paths must be canonical lexical mount paths')",
        "    return value",
        "",
        "",
        "def _validate_base64_unpadded(value: str) -> str:",
        "    if '=' in value or re.fullmatch(r'[A-Za-z0-9+/]*', value) is None:",
        "        raise ValueError('encoded bytes must use unpadded base64')",
        "    try:",
        "        decoded = base64.b64decode(value + ('=' * (-len(value) % 4)), validate=True)",
        "    except (binascii.Error, ValueError) as error:",
        "        raise ValueError('encoded bytes must use unpadded base64') from error",
        "    if base64.b64encode(decoded).decode('ascii').rstrip('=') != value:",
        "        raise ValueError('encoded bytes must use canonical unpadded base64')",
        "    return value",
        "",
        "",
        "def _timestamp_fraction(nanoseconds: int) -> str:",
        "    if nanoseconds == 0:",
        "        return ''",
        "    if nanoseconds % 1_000_000 == 0:",
        "        return f'.{nanoseconds // 1_000_000:03d}'",
        "    if nanoseconds % 1_000 == 0:",
        "        return f'.{nanoseconds // 1_000:06d}'",
        "    return f'.{nanoseconds:09d}'",
        "",
        "",
        "def _normalize_eip_timestamp(value: object) -> str:",
        "    if isinstance(value, datetime):",
        "        if value.tzinfo is None or value.utcoffset() is None:",
        "            raise ValueError('EIP timestamps must include a UTC offset')",
        "        nanoseconds = value.microsecond * 1_000",
        "        normalized = value.astimezone(timezone.utc).replace(microsecond=0)",
        "    elif isinstance(value, str):",
        "        match = re.fullmatch(",
        "            r'(?P<base>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2})'",
        "            r'(?:\\.(?P<fraction>[0-9]{1,9}))?(?P<zone>Z|[+-][0-9]{2}:[0-9]{2})',",
        "            value,",
        "        )",
        "        if match is None:",
        "            raise ValueError('EIP timestamps must use RFC 3339 syntax')",
        "        fraction = match.group('fraction') or ''",
        "        nanoseconds = int(fraction.ljust(9, '0')) if fraction else 0",
        "        zone = match.group('zone')",
        "        offset = '+00:00' if zone == 'Z' else zone",
        "        try:",
        "            normalized = datetime.fromisoformat(f\"{match.group('base')}{offset}\").astimezone(timezone.utc)",
        "        except ValueError as error:",
        "            raise ValueError('EIP timestamp is outside the RFC 3339 calendar') from error",
        "    else:",
        "        raise ValueError('EIP timestamps must be RFC 3339 strings or datetime values')",
        "    prefix = (",
        "        f'{normalized.year:04d}-{normalized.month:02d}-{normalized.day:02d}'",
        "        f'T{normalized.hour:02d}:{normalized.minute:02d}:{normalized.second:02d}'",
        "    )",
        "    return ''.join(prefix) + _timestamp_fraction(nanoseconds) + 'Z'",
        "",
        "",
        "Identifier = Annotated[StrictStr, Field(min_length=1)]",
        "AbsoluteEIPPath = Annotated[",
        "    StrictStr,",
        "    Field(json_schema_extra={'format': 'eip-absolute-path'}),",
        "    AfterValidator(_validate_absolute_eip_path),",
        "]",
        "Base64Unpadded = Annotated[",
        "    StrictStr,",
        "    Field(json_schema_extra={'format': 'eip-base64-unpadded'}),",
        "    AfterValidator(_validate_base64_unpadded),",
        "]",
        "ProtocolVersion = Annotated[StrictStr, Field(pattern=r'^[1-9][0-9]*\\.[0-9]+$')]",
        "EIPTimestamp = Annotated[",
        "    StrictStr,",
        "    Field(json_schema_extra={'format': 'date-time'}),",
        "    BeforeValidator(_normalize_eip_timestamp),",
        "]",
        "",
        "",
        "class EIPModel(BaseModel):",
        "    model_config = ConfigDict(extra='forbid', frozen=True)",
        "",
    ]

    public_names: list[str] = []
    error_code_values: list[tuple[str, str, int]] = []
    for _, enum in sorted(index.enums.items()):
        if enum.name in TOOLING_ENUMS:
            continue
        values = _enum_values(enum, options)
        if not values:
            continue
        public_names.append(enum.name)
        lines.extend(["", f"class {enum.name}(StrEnum):"])
        lines.extend(f"    {member} = {json_name!r}" for member, json_name in values)
        if enum.name == "ErrorType":
            error_code_values = _error_code_values(enum, options)

    if not error_code_values:
        raise ValueError("EIP ErrorType has no code mapping")
    lines.extend(["", "EIP_ERROR_CODES: Final[Mapping[ErrorType, int]] = MappingProxyType({"])
    lines.extend(f"    ErrorType.{member}: {code}," for member, _, code in error_code_values)
    lines.extend(["})", ""])
    public_names.append("EIP_ERROR_CODES")

    model_classes: list[str] = []
    for _, message in topological_messages(index):
        if message.name in TOOLING_MESSAGES:
            continue
        message_option = options.message(message)
        if message_option is not None and message_option.discriminated_union:
            oneofs = real_oneofs(message)
            if len(oneofs) != 1:
                raise ValueError(f"discriminated union {message.name} must contain exactly one oneof")
            variants = [short_name(field.type_name) for field in next(iter(oneofs.values()))]
            public_names.append(message.name)
            lines.extend(
                [
                    "",
                    f"type {message.name} = Annotated[",
                    f"    {' | '.join(variants)},",
                    "    Field(discriminator='kind'),",
                    "]",
                ]
            )
            continue
        if message_option is not None and message_option.transparent:
            if len(message.field) != 1:
                raise ValueError(f"transparent message {message.name} must have exactly one field")
            annotation = _base_field_type(message.field[0], index, options)
            public_names.append(message.name)
            model_classes.append(message.name)
            lines.extend(
                [
                    "",
                    f"class {message.name}(RootModel[{annotation}]):",
                    "    model_config = ConfigDict(frozen=True)",
                    f"    root: {annotation}",
                ]
            )
            continue

        public_names.append(message.name)
        model_classes.append(message.name)
        lines.extend(["", f"class {message.name}(EIPModel):"])
        if not message.field:
            lines.append("    pass")
        for field in message.field:
            annotation, default = _field_annotation(field, message, index, options)
            suffix = "" if default is None else f" = {default}"
            lines.append(f"    {field.name}: {annotation}{suffix}")

        oneofs = real_oneofs(message)
        for index_number, fields in oneofs.items():
            names = [field.name for field in fields]
            validator_name = message.oneof_decl[index_number].name
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    f"    def _validate_{validator_name}(self) -> {message.name}:",
                    "        present = sum(",
                    f"            value is not None for value in ({', '.join(f'self.{name}' for name in names)},)",
                    "        )",
                    "        if present != 1:",
                    f"            raise ValueError('exactly one of {', '.join(names)} must be present')",
                    "        return self",
                ]
            )
        if message.name == "OutputPolicy":
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    "    def _validate_output_bounds(self) -> OutputPolicy:",
                    "        if self.max_inline_bytes > self.max_output_bytes:",
                    "            raise ValueError('max_inline_bytes cannot exceed max_output_bytes')",
                    "        return self",
                ]
            )
        if message.name == "OutputCapture":
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    "    def _validate_capture_structure(self) -> OutputCapture:",
                    "        if self.available_start > self.available_end:",
                    "            raise ValueError('available_start cannot exceed available_end')",
                    "        if self.kind is OutputKind.EMPTY:",
                    "            if (",
                    "                self.produced_bytes != 0",
                    "                or self.captured_bytes != 0",
                    "                or self.dropped_bytes != 0",
                    "                or self.available_start != 0",
                    "                or self.available_end != 0",
                    "                or any(",
                    "                    value is not None",
                    "                    for value in (",
                    "                        self.inline,",
                    "                        self.preview,",
                    "                        self.reference,",
                    "                        self.cursor,",
                    "                        self.expires_at,",
                    "                    )",
                    "                )",
                    "            ):",
                    "                raise ValueError('empty output must contain no bytes or retained state')",
                    "        elif self.kind is OutputKind.INLINE:",
                    "            if self.inline is None or any(",
                    "                value is not None",
                    "                for value in (self.preview, self.reference, self.cursor, self.expires_at)",
                    "            ):",
                    "                raise ValueError('inline output requires only inline data')",
                    "        elif self.kind is OutputKind.RETAINED:",
                    "            if self.reference is None or self.inline is not None or self.expires_at is None:",
                    "                raise ValueError('retained output requires a reference and expiry')",
                    "        elif self.kind is OutputKind.TRUNCATED and any(",
                    "            value is not None",
                    "            for value in (self.inline, self.reference, self.cursor, self.expires_at)",
                    "        ):",
                    "            raise ValueError('truncated output cannot contain retained or inline state')",
                    "        return self",
                ]
            )
        if message.name == "EIPLimits":
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    "    def _validate_limit_relationships(self) -> EIPLimits:",
                    "        if self.max_inline_output_bytes > self.max_output_bytes:",
                    "            raise ValueError('max_inline_output_bytes cannot exceed max_output_bytes')",
                    "        if self.max_processes > self.max_process_records:",
                    "            raise ValueError('max_processes cannot exceed max_process_records')",
                    "        if self.max_concurrent_operations > self.max_operation_records:",
                    "            raise ValueError('max_concurrent_operations cannot exceed max_operation_records')",
                    "        return self",
                ]
            )
        if message.name == "EIPErrorData":
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    "    def _validate_retention_gap_bounds(self) -> EIPErrorData:",
                    "        available_start = self.available_start",
                    "        available_end = self.available_end",
                    "        has_start = available_start is not None",
                    "        has_end = available_end is not None",
                    "        if has_start != has_end:",
                    "            raise ValueError('available_start and available_end must be present together')",
                    "        if self.error_type is ErrorType.RETENTION_GAP and not has_start:",
                    "            raise ValueError('retention_gap requires available bounds')",
                    "        if (",
                    "            available_start is not None",
                    "            and available_end is not None",
                    "            and available_start > available_end",
                    "        ):",
                    "            raise ValueError('available_start cannot exceed available_end')",
                    "        return self",
                ]
            )
        if message.name == "EIPError":
            lines.extend(
                [
                    "",
                    "    @model_validator(mode='after')",
                    "    def _validate_error_code(self) -> EIPError:",
                    "        if self.code != EIP_ERROR_CODES[self.data.error_type]:",
                    "            raise ValueError('JSON-RPC code does not match error_type')",
                    "        return self",
                ]
            )

    lines.extend(["", ""])
    for name in model_classes:
        if name not in NO_REBUILD_MODELS:
            lines.append(f"{name}.model_rebuild()")
    lines.extend(["", "__all__ = ["])
    lines.extend(f"    {name!r}," for name in sorted(public_names))
    lines.extend(["]", ""])
    return "\n".join(lines)


def method_records(index: SchemaIndex, options: OptionReader) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for method in index.methods:
        option = options.method(method)
        kind = options.enum_name("MethodKind", option.kind).removeprefix("METHOD_KIND_").lower()
        idempotency = (
            options.enum_name("IdempotencyClass", option.idempotency).removeprefix("IDEMPOTENCY_CLASS_").lower()
        )
        key_mode = (
            options.enum_name("IdempotencyKeyMode", option.idempotency_key)
            .removeprefix("IDEMPOTENCY_KEY_MODE_")
            .lower()
        )
        error_family = options.enum_name("ErrorFamily", option.error_family).removeprefix("ERROR_FAMILY_").lower()
        result_type = None if method.output_type == ".google.protobuf.Empty" else short_name(method.output_type)
        records.append(
            {
                "rpc_name": method.name,
                "jsonrpc_method": option.jsonrpc_method,
                "capability": option.capability or None,
                "kind": kind,
                "idempotency": idempotency,
                "idempotency_key": key_mode,
                "introduced": f"{option.introduced_major}.{option.introduced_minor}",
                "error_family": error_family,
                "params_type": short_name(method.input_type),
                "result_type": result_type,
            }
        )
    names: set[str] = set()
    for record in records:
        name = record["jsonrpc_method"]
        if not isinstance(name, str) or not name:
            raise ValueError(f"EIP method {record['rpc_name']} has no JSON-RPC name")
        if name in names:
            raise ValueError(f"duplicate EIP JSON-RPC method: {name}")
        names.add(name)
        if record["kind"] != "request_response":
            raise ValueError(f"EIP 1.0 method {name} must use correlated request-response")
        if record["idempotency"] == "unspecified":
            raise ValueError(f"EIP method {name} has unspecified idempotency")
        if record["idempotency_key"] == "unspecified":
            raise ValueError(f"EIP method {name} has unspecified idempotency-key mode")
        if record["error_family"] == "unspecified":
            raise ValueError(f"EIP method {name} has unspecified error family")
        if record["introduced"].startswith("0."):
            raise ValueError(f"EIP method {name} has invalid introduced version")
        if record["result_type"] is None:
            raise ValueError(f"EIP request-response method {name} must have a result message")
    records.sort(key=lambda record: record["jsonrpc_method"])
    return records


def render_methods(records: list[dict[str, Any]]) -> str:
    model_names = sorted(
        {record["params_type"] for record in records}
        | {record["result_type"] for record in records if record["result_type"]}
    )
    lines = [
        GENERATED_HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from types import MappingProxyType",
        "from typing import Literal",
        "",
        f"from .models import {', '.join(model_names)}",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class MethodSpec[P, R]:",
        "    name: str",
        "    capability: str | None",
        "    kind: Literal['request_response']",
        "    idempotency: str",
        "    idempotency_key: Literal['disallowed', 'optional', 'required']",
        "    introduced: str",
        "    error_family: str",
        "    params_type: type[P]",
        "    result_type: type[R]",
        "",
    ]
    constants: list[str] = []
    for record in records:
        constant = re.sub(r"[^A-Za-z0-9]+", "_", record["jsonrpc_method"]).upper()
        constants.append(constant)
        lines.extend(
            [
                "",
                f"{constant} = MethodSpec(",
                f"    name={record['jsonrpc_method']!r},",
                f"    capability={record['capability']!r},",
                f"    kind={record['kind']!r},",
                f"    idempotency={record['idempotency']!r},",
                f"    idempotency_key={record['idempotency_key']!r},",
                f"    introduced={record['introduced']!r},",
                f"    error_family={record['error_family']!r},",
                f"    params_type={record['params_type']},",
                f"    result_type={record['result_type']},",
                ")",
            ]
        )
    lines.extend(
        [
            "",
            "METHODS = MappingProxyType({",
            *[f"    {constant}.name: {constant}," for constant in constants],
            "})",
            "",
        ]
    )
    return "\n".join(lines)


def render_client(records: list[dict[str, Any]]) -> str:
    model_names = sorted({record["params_type"] for record in records} | {record["result_type"] for record in records})
    constants = [re.sub(r"[^A-Za-z0-9]+", "_", record["jsonrpc_method"]).upper() for record in records]
    lines = [
        GENERATED_HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from typing import Protocol",
        "",
        f"from .methods import MethodSpec, {', '.join(constants)}",
        f"from .models import {', '.join(model_names)}",
        "",
        "",
        "class EIPRequester(Protocol):",
        "    async def request[P, R](self, method: MethodSpec[P, R], params: P) -> R: ...",
        "",
        "",
        "class EIPClient:",
        "    def __init__(self, requester: EIPRequester) -> None:",
        "        self._requester = requester",
    ]
    for record, constant in zip(records, constants, strict=True):
        function_name = record["jsonrpc_method"].replace(".", "_")
        lines.extend(
            [
                "",
                f"    async def {function_name}(self, params: {record['params_type']}) -> {record['result_type']}:",
                f"        return await self._requester.request({constant}, params)",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def render_codec() -> str:
    return (
        GENERATED_HEADER
        + """from __future__ import annotations

import json

from pydantic import BaseModel, TypeAdapter


def _object_without_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    value: dict[str, object] = {}
    for key, item in pairs:
        if key in value:
            raise ValueError(f"duplicate JSON field: {key}")
        value[key] = item
    return value


def encode_model(value: BaseModel) -> bytes:
    candidate = value.model_dump(mode="python", round_trip=True, warnings="error")
    validated = type(value).model_validate(candidate)
    data = validated.model_dump(mode="json", exclude_unset=True, exclude_defaults=True, warnings="error")
    return json.dumps(data, ensure_ascii=False, allow_nan=False, separators=(",", ":"), sort_keys=True).encode("utf-8")


def decode_model[T](payload: bytes | str, model_type: type[T]) -> T:
    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")
    data = json.loads(
        payload,
        object_pairs_hook=_object_without_duplicates,
        parse_constant=lambda value: (_ for _ in ()).throw(ValueError(f"invalid JSON number: {value}")),
    )
    return TypeAdapter(model_type).validate_python(data)
"""
    )


def render_protocol(descriptor_sha256: str) -> str:
    return (
        GENERATED_HEADER
        + f'''from __future__ import annotations

from typing import Annotated, Final, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, model_validator

from .models import EIPError

EIP_PROTOCOL_VERSION: Final = "1.0"
EIP_PROTOCOL_MAJOR: Final = 1
EIP_PROTOCOL_MINOR: Final = 0
EIP_PROTO_PACKAGE: Final = "converge.agent_envd.eip.v1"
EIP_DESCRIPTOR_SHA256: Final = "{descriptor_sha256}"

type JsonRpcId = StrictStr | Annotated[StrictInt, Field(ge=-(2**63), le=2**63 - 1)]


class JsonRpcEnvelope(BaseModel):
    model_config = ConfigDict(extra="ignore", frozen=True)

    @model_validator(mode="before")
    @classmethod
    def _reject_reserved_extensions(cls, value: object) -> object:
        if isinstance(value, dict):
            unknown = set(value) - set(cls.model_fields)
            reserved = sorted(name for name in unknown if isinstance(name, str) and name.startswith("eip_"))
            if reserved:
                raise ValueError(f"unknown reserved JSON-RPC field: {{reserved[0]}}")
        return value


class JsonRpcRequest(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    method: StrictStr
    params: dict[str, object]


class JsonRpcSuccessResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId
    result: dict[str, object]


class JsonRpcErrorResponse(JsonRpcEnvelope):
    jsonrpc: Literal["2.0"]
    id: JsonRpcId | None
    error: EIPError
'''
    )


def render_init(index: SchemaIndex, options: OptionReader) -> str:
    model_names = {message.name for message in index.messages.values() if message.name not in TOOLING_MESSAGES}
    model_names.update(
        enum.name for enum in index.enums.values() if enum.name not in TOOLING_ENUMS and _enum_values(enum, options)
    )
    public_models = sorted(model_names)
    lines = [
        GENERATED_HEADER.rstrip(),
        "from .client import EIPClient, EIPRequester",
        "from .codec import decode_model, encode_model",
        "from .methods import METHODS, MethodSpec",
        f"from .models import EIP_ERROR_CODES, {', '.join(public_models)}",
        "from .protocol import (",
        "    EIP_DESCRIPTOR_SHA256,",
        "    EIP_PROTOCOL_MAJOR,",
        "    EIP_PROTOCOL_MINOR,",
        "    EIP_PROTOCOL_VERSION,",
        "    EIP_PROTO_PACKAGE,",
        "    JsonRpcEnvelope,",
        "    JsonRpcErrorResponse,",
        "    JsonRpcId,",
        "    JsonRpcRequest,",
        "    JsonRpcSuccessResponse,",
        ")",
        "",
        "__all__ = [",
        "    'EIPClient',",
        "    'EIPRequester',",
        "    'MethodSpec',",
        "    'METHODS',",
        "    'encode_model',",
        "    'decode_model',",
        "    'EIP_DESCRIPTOR_SHA256',",
        "    'EIP_PROTOCOL_MAJOR',",
        "    'EIP_PROTOCOL_MINOR',",
        "    'EIP_PROTOCOL_VERSION',",
        "    'EIP_PROTO_PACKAGE',",
        "    'EIP_ERROR_CODES',",
        "    'JsonRpcEnvelope',",
        "    'JsonRpcErrorResponse',    'JsonRpcId',",
        "    'JsonRpcRequest',",
        "    'JsonRpcSuccessResponse',",
        *[f"    {name!r}," for name in public_models],
        "]",
        "",
    ]
    return "\n".join(lines)


def write_python_surface(
    output_dir: Path,
    index: SchemaIndex,
    options: OptionReader,
    descriptor_sha256: str,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    records = method_records(index, options)
    outputs = {
        "models.py": render_models(index, options),
        "methods.py": render_methods(records),
        "client.py": render_client(records),
        "codec.py": render_codec(),
        "protocol.py": render_protocol(descriptor_sha256),
        "__init__.py": render_init(index, options),
    }
    paths: list[Path] = []
    for name, content in outputs.items():
        path = output_dir / name
        path.write_text(content, encoding="utf-8")
        paths.append(path)
    return paths
